### ISSUE TITLE
NPE on metrics writer

### ISSUE THREAD

**Issue by liu-aoao** [alibaba/Sentinel#1043]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

When running Sentinel on our server, we noticed errors below: 
```
A 2019-09-12T23:27:38Z 2019-09-12 23:27:38.172 WARNING [MetricTimerListener] Write metric error
 
A 2019-09-12T23:27:38Z java.lang.NullPointerException
	at com.alibaba.csp.sentinel.node.metric.MetricWriter.nextFileNameOfDay(MetricWriter.java:198)
	at com.alibaba.csp.sentinel.node.metric.MetricWriter.write(MetricWriter.java:136)
	at com.alibaba.csp.sentinel.node.metric.MetricTimerListener.run(MetricTimerListener.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Describe what you expected to happen

We are setting log output to console using `-Dcsp.sentinel.log.output.type=console`, and the above error log does find in the console. However seems the `MetricsWriter` class is still trying to access a file, where on our system it's not possible. 

I think when the config is set to using the console, no class should try to access files. 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

Google AppEngine Flex Java8

**Comment by linlinisme** [comment]
It seems that  the `logBaseDir` it is not a file dir but a file.  @liu-aoao would you please check `csp.sentinel.log.dir`  is a file dir ?

**Comment by sczyh30** [comment]
Any feedback? @liu-aoao

**Comment by sczyh30** [comment]
Closing this inactive issue.
