### ISSUE TITLE
sentinel-dashboard-1.6.3 cpu 100%

### ISSUE THREAD

**Issue by wenit** [alibaba/Sentinel#1083]
## Issue Description

Type: *bug report*

### Describe what you expected to happen
sentinel-dashboard-1.6.3 进程占用 cpu 100%

### How to reproduce it (as minimally and precisely as possible)

1. 启动sentinel-dashboard-1.6.3
2. spring boot 集成 sentinel-transport-simple-http 1.6.3
3. 多次使用wrk进行压测，每次10分钟，然后停止压测，并停止spring boot程序
4. 放置一晚上无任何操作，第二天发现sentinel-dashboard-1.6.3 进程占用100%cpu

### Tell us your environment

电脑配置：i7 8C + 16G
win10 + jdk1.8

### Anything else we need to know?

NONE

**Comment by sczyh30** [comment]
Could you please provide more information (e.g. the call stack of the thread with high CPU usage)?

**Comment by wenit** [comment]
## 再次复现

2019年10月15日 上午11点，我再次启动服务，并进行了2次压测，然后停止压测，并经应用程序关闭，只启动了sentinel-dashboard，到下午1点半的时候出现再次出现CPU 100%

### CPU 100% 截图

![CPU100%](https://user-images.githubusercontent.com/12817195/66803448-3c53ea80-ef52-11e9-9432-f16055505c17.png)

### 出现异常时，抓取的线程stack

[sentinel-dashboard-stack.txt](https://github.com/alibaba/Sentinel/files/3727513/sentinel-dashboard-stack.txt)

**Comment by sczyh30** [comment]
可否看一下具体是哪个线程 CPU 占用高？

**Comment by linlinisme** [comment]
"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00000000034b7800 nid=0x2ad4 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00000000034b9000 nid=0x23e0 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00000000034ba800 nid=0x804 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00000000034bd000 nid=0x37a0 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00000000034bf000 nid=0x1e34 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00000000034c0800 nid=0x14e8 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00000000034c3800 nid=0x4314 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00000000034c4800 nid=0xa28 runnable

**Comment by chakra-coder** [comment]
可以提供一下jvm的配置信息么 @wenit

**Comment by wenit** [comment]
@chakra-coder @sczyh30 2位大佬详细的如下，大概2个小时会出现，我会尝试在linux服务器运行，看看是否有问题，看线程栈，感觉是nio poll死循环导致。

## sentinel-dashboard服务启动参数

``` bash
java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dcsp.sentinel.api.port=18719 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard-1.6.3.jar
```

## JVM Dashborad

![jvm-dashboard](https://user-images.githubusercontent.com/12817195/66834084-97f09900-ef8f-11e9-9210-bb4d4271b9c9.png)

## Thread CPU Top

![thread-top](https://user-images.githubusercontent.com/12817195/66834071-91622180-ef8f-11e9-9259-d8904e7f83e8.png)

## Thread Cpu Top stack

![thread-top-stack](https://user-images.githubusercontent.com/12817195/66834067-90c98b00-ef8f-11e9-8b2e-af03d3f47eb4.png)

## Thread Cpu Top stack2

![thread-top-stack2](https://user-images.githubusercontent.com/12817195/66834069-90c98b00-ef8f-11e9-8aab-79626875cd8e.png)

## Full all thread stack
[sentinel-dashboard-stack-7104.txt](https://github.com/alibaba/Sentinel/files/3729386/sentinel-dashboard-stack-7104.txt)

**Comment by wenit** [comment]
我在Centos 7.4 的服务器上运行sentinel-dashboard-1.6.3 并未出现CPU使用率100%问题。

**Comment by jasonjoo2010** [comment]
Pay attention here:

```
"I/O dispatcher 32" #58 prio=5 os_prio=0 tid=0x0000000024b2c800 nid=0x12c8 waiting on condition [0x00000000291fe000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c28373f0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(Unknown Source)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(Unknown Source)
	at java.util.concurrent.locks.ReentrantLock.lock(Unknown Source)
	at ch.qos.logback.core.OutputStreamAppender.writeBytes(OutputStreamAppender.java:197)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:231)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.error(Logger.java:526)
	at com.alibaba.csp.sentinel.dashboard.metric.MetricFetcher$2.failed(MetricFetcher.java:233)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:376)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Unknown Source)
```


Is there so many logs? What does it say?

**Comment by wenit** [comment]
Have you found the cause of this problem?

**Comment by sczyh30** [comment]
> Have you found the cause of this problem? @sczyh30

Not yet. Did this problem occur regularly?
