### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by lw5946** [alibaba/Sentinel#1085]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
When I compile and run sentinel-dashboard according to readme, an error is reported.
```java
INFO: log name use pid is: false
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/util/unit/DataSize
	at org.springframework.boot.convert.StringToDataSizeConverter.getConvertibleTypes(StringToDataSizeConverter.java:40)
	at org.springframework.core.convert.support.GenericConversionService$Converters.add(GenericConversionService.java:507)
	at org.springframework.core.convert.support.GenericConversionService.addConverter(GenericConversionService.java:105)
	at org.springframework.boot.convert.ApplicationConversionService.addApplicationConverters(ApplicationConversionService.java:107)
	at org.springframework.boot.convert.ApplicationConversionService.configure(ApplicationConversionService.java:91)
	at org.springframework.boot.convert.ApplicationConversionService.<init>(ApplicationConversionService.java:52)
	at org.springframework.boot.convert.ApplicationConversionService.<init>(ApplicationConversionService.java:45)
	at org.springframework.boot.convert.ApplicationConversionService.getSharedInstance(ApplicationConversionService.java:71)
	at org.springframework.boot.SpringApplication.configureEnvironment(SpringApplication.java:470)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at com.alibaba.csp.sentinel.dashboard.DashboardApplication.main(DashboardApplication.java:33)
Caused by: java.lang.ClassNotFoundException: org.springframework.util.unit.DataSize
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

### Tell us your environment
sentinel: 1.6.3
OS: win 10

**Comment by lw5946** [comment]
Using Linux OS, the same error is reported.

**Comment by lw5946** [comment]
Version 1.6.2 was successful.

**Comment by lw5946** [comment]
Sorry, it's a problem caused by my expansion of the source code.

**Comment by xADMx** [comment]
Я решил эту проблему указав в pom.xml:
`<package>jar<package>`
