### ISSUE TITLE
ConnectionException: connection refused when fetching metrics from the client side

### ISSUE THREAD

**Issue by Force-King** [alibaba/Sentinel#1157]
控制台没有显示客户端信息，app已经显示连接，但是没有具体埋点数据；
控制台日志打印，被拒绝，报错如下：

`2019-11-14 14:44:44 [pool-11-thread-1] ERROR c.a.c.s.d.metric.MetricFetcher - Failed to fetch metric from <http://xxx.xxx.xx.xxx:8719/metric?startTime=1573713876000&endTime=1573713882000&refetch=false> (ConnectionException: 拒绝连接)
2019-11-14 15:12:29 [http-nio-8080-exec-7] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:428)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`

加了tomcat 配置：
             maxHttpHeaderSize="8192"

还是报：
`ERROR c.a.c.s.d.metric.MetricFetcher - Failed to fetch metric from <http://xxx.xxx.xx.xxx:8719/metric?startTime=1573724411000&endTime=1573724417000&refetch=false> (ConnectionException: 拒绝连接)`

telnet 端口 均可以，而且是内部局域网，没有其他限制，请各位大神帮帮忙。。。

**Comment by sczyh30** [comment]
You may check whether the network from the dashboard to the client side is accessible, and the client IP is correct.

**Comment by Force-King** [comment]
> You may check whether the network from the dashboard to the client side is accessible, and the client IP is correct.

The network can be accessed, there is no problem with the client ip configuration.

**Comment by sczyh30** [comment]
Please check according to [the FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ).

**Comment by Force-King** [comment]
@sczyh30 已经按照 FAQ 排查了好几遍了，配置均没有问题，本地 mac 启动控制台也可以查看，放到 测试环境 和线上就不行。
以下是日志，没有报错。
record:
`www@m180p12 sentinel]$ ls
command-center.log.pid14404.2019-11-19.0      sentinel-record.log.pid14404.2019-11-19.0
command-center.log.pid14404.2019-11-19.0.lck  sentinel-record.log.pid14404.2019-11-19.0.lck
[www@m180p12 sentinel]$ cat sentinel-record.log.pid14404.2019-11-19.0
2019-11-19 16:16:29.200 INFO [InitExecutor] Found init func: com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit
2019-11-19 16:16:29.204 INFO [InitExecutor] Found init func: com.alibaba.csp.sentinel.init.ParamFlowStatisticSlotCallbackInit
2019-11-19 16:16:29.205 INFO [InitExecutor] Found init func: com.alibaba.csp.sentinel.transport.init.CommandCenterInitFunc
2019-11-19 16:16:29.209 INFO [InitExecutor] Found init func: com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc
2019-11-19 16:16:29.219 INFO [SpiLoader] Found CommandCenter SPI: com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter with order 2147483647
2019-11-19 16:16:29.222 INFO [CommandCenterProvider] CommandCenter resolved: com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter
2019-11-19 16:16:29.340 INFO App name resolved: hermes-web
2019-11-19 16:16:29.354 INFO [SentinelConfig] Application type resolved: 0
2019-11-19 16:16:29.373 INFO [CommandCenterInit] Starting command center: com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter
2019-11-19 16:16:29.374 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.transport.init.CommandCenterInitFunc with order -1
2019-11-19 16:16:29.411 INFO [SimpleHttpHeartbeatSender] Default console address list retrieved: [localhost/127.0.0.1:8900]
2019-11-19 16:16:29.412 INFO [SpiLoader] Found HeartbeatSender SPI: com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender with order 2147483647
2019-11-19 16:16:29.413 INFO [HeartbeatSenderProvider] HeartbeatSender activated: com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender
2019-11-19 16:16:29.416 INFO [HeartbeatSenderInit] Heartbeat interval not configured in config property or invalid, using sender default: 10000
2019-11-19 16:16:29.421 INFO [HeartbeatSenderInit] HeartbeatSender started: com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender
2019-11-19 16:16:29.422 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc with order -1
2019-11-19 16:16:29.429 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit with order 2147483647
2019-11-19 16:16:29.438 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.init.ParamFlowStatisticSlotCallbackInit with order 2147483647
2019-11-19 16:16:38.190 INFO [SystemRuleManager] Current system check status: false, highestSystemLoad: 1.797693e+308, highestCpuUsage: 1.797693e+308, maxRt: 9223372036854775807, maxThread: 9223372036854775807, maxQps: 1.797693e+308
[www@m180p12 sentinel]$`

`[www@m180p12 sentinel]$ cat command-center.log.pid14404.2019-11-19.0
2019-11-19 16:16:29.385 INFO [CommandCenter] Begin listening at port 8719
2019-11-19 16:16:35.713 INFO [SimpleHttpCommandCenter] socket income: GET /jsonTree?type=root HTTP/1.1,/192.168.180.12
2019-11-19 16:16:36.112 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /jsonTree?type=root HTTP/1.1, address: /192.168.180.12, time cost: 400 ms
2019-11-19 16:16:36.618 INFO [SimpleHttpCommandCenter] socket income: GET /jsonTree?type=root HTTP/1.1,/192.168.180.12
2019-11-19 16:16:36.621 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /jsonTree?type=root HTTP/1.1, address: /192.168.180.12, time cost: 4 ms
2019-11-19 16:16:38.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151390000&endTime=1574151396000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:16:38.193 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151390000&endTime=1574151396000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 33 ms
2019-11-19 16:16:45.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151397000&endTime=1574151403000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:16:45.165 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151397000&endTime=1574151403000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 6 ms
2019-11-19 16:16:52.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151404000&endTime=1574151410000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:16:52.162 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151404000&endTime=1574151410000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 3 ms
2019-11-19 16:16:59.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151411000&endTime=1574151417000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:16:59.162 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151411000&endTime=1574151417000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 3 ms
2019-11-19 16:17:06.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151418000&endTime=1574151424000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:17:06.162 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151418000&endTime=1574151424000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 2 ms
2019-11-19 16:17:13.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151425000&endTime=1574151431000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:17:13.161 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151425000&endTime=1574151431000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 2 ms
2019-11-19 16:17:20.167 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151432000&endTime=1574151438000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:17:20.168 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151432000&endTime=1574151438000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 2 ms
2019-11-19 16:17:27.160 INFO [SimpleHttpCommandCenter] socket income: GET /metric?startTime=1574151439000&endTime=1574151445000&refetch=false HTTP/1.1,/192.168.180.12
2019-11-19 16:17:27.161 INFO [SimpleHttpCommandCenter] Deal a socket task: GET /metric?startTime=1574151439000&endTime=1574151445000&refetch=false HTTP/1.1, address: /192.168.180.12, time cost: 2 ms`

dashboard 也没有报错日志，在此过程中，我一直有请求，但控制台依旧不显示应用。

**Comment by Force-King** [comment]
以下方式均已尝试：
1. https://github.com/alibaba/Sentinel/issues/847
2. 每个应用JVM参数增加 -Dcsp.sentinel.api.port= 不同的端口
3. 检查各个linux 服务器，date 时间均一致
4. telnet ip port ， 可通
5. netstat 检查控制台端口处于监听状态

@sczyh30 还有什么地方可能造成控制台不显示吗？ 本地可以，所以应该不是程序的问题，很大可能是网络问题，但是网络方面我能想到的都检查了。

**Comment by Force-King** [comment]
@sczyh30  补充一下，今天又过了一遍sentinel源码，确定是SimpleHttpCommandCenter 中的 “sentinel-command-center-executor” 和 “sentinel-command-center-service-executor”  Thread没有创建。按理说初始化会调用 commandCenter.start();  很奇怪，还没有找到原因。。。

**Comment by sczyh30** [comment]
本地启动和测试环境启动方式是一样的么？如果有 shade 的话，配置是否正确？类加载器有没有差异？这个像是类加载器问题导致 SPI 扫不到。另外 1.7.0 版本改进了 SPI 的类加载器机制，可以升到 1.7.0 试一下。

It seems that the SPIs in other modules were not loaded (maybe related to the ClassLoader). Sentinel 1.7.0 improved the SPI classloader mechanism (#1087). Maybe you could try Sentinel 1.7.0.

**Comment by Force-King** [comment]
@sczyh30 已经解决，谢谢啦，可以关闭了
pom加了以下配置就好了：
```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <transformers>      
                             <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                        </transformers>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by sundong1982** [comment]
我从1.6.0升级到1.6.3时也遇到过此问题，后来发现是因为我的客户端时间和服务器端时间不同步，但1.6.0版本就是不同步也是正常运行，估计是升级后改了时间判断的方式。不知道楼主 @sczyh30 解决此问题，在pom加plugin的配置是在哪加的，sentinel-dashboard还是客户端？
