### ISSUE TITLE
when highestCpuUsage SystemRule is configured, the cpu usage become fluctuate widely

### ISSUE THREAD

**Issue by fangwentong** [alibaba/Sentinel#1206]
## Issue Description

 #1050 deprecate bbr period of maxCpuUsage strategy, after that, the system cpu usage become less stable in second period level.
Since the CPU usage value held in `SystemStatusListener` updates every seconds, #1050  means that if CPU usage exceed threshold, all the traffic in next second will be blocked, and the cpu maybe fallen to an very low usage, so all the traffic in the second  after next will pass, cpu usage back to an too high level, and so on.

### Describe what you expected to happen

A relative steady cpu usage are expected when highestCpuUsage is configured.

**Comment by sczyh30** [comment]
Thanks for your suggestion. This will be improved in later versions.

**Comment by leilei2018** [comment]
I noticed that too! cpu is high
the SystemStatusListener  Scheduled too frequently!

Suggest optimization define a switch for   start/stop  like  future.cancel/execute future

**Comment by bbenguo** [comment]
top -Hp 458080
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
**458206 service   20   0 5870220   1.4g   9724 R 99.0 34.3   3608:23 java**
458205 service   20   0 5870220   1.4g   9724 S  1.6 34.3 123:30.21 java
463939 service   20   0 5870220   1.4g   9724 S  1.6 34.3   3:38.50 java
458156 service   20   0 5870220   1.4g   9724 S  0.3 34.3   2:33.43 java
458210 service   20   0 5870220   1.4g   9724 S  0.3 34.3   0:13.32 java
458080 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:00.00 java
458089 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:20.81 java
458090 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:46.72 java
458091 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:46.72 java
458092 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:13.32 java
458093 service   20   0 5870220   1.4g   9724 S  0.0 34.3   2:50.83 java
458094 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:00.17 java
458095 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:00.16 java
458096 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:00.00 java
458097 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:00.00 java
458098 service   20   0 5870220   1.4g   9724 S  0.0 34.3   1:25.34 java
458099 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:18.25 java
458100 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:02.90 java
458101 service   20   0 5870220   1.4g   9724 S  0.0 34.3   5:56.71 java
458151 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:02.69 java
458152 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:03.06 java
458153 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:06.97 java
458155 service   20   0 5870220   1.4g   9724 S  0.0 34.3   0:04.74 java

"sentinel-system-status-record-task-thread-1" #71 daemon prio=5 os_prio=0 tid=0x00007fe4cd1a3000 nid=**0x6fdde** runnable [0x00007fe46fccd000]
   java.lang.Thread.State: RUNNABLE
	at sun.management.OperatingSystemImpl.getSystemCpuLoad(Native Method)
	**at com.alibaba.csp.sentinel.slots.system.SystemStatusListener.run(SystemStatusListener.java:57)**
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
