### ISSUE TITLE
dubbo2.7.5版本不兼容

### ISSUE THREAD

**Issue by warrior701** [alibaba/Sentinel#1292]
## java.lang.AbstractMethodError

Type: *bug report* 

Caused by: java.lang.AbstractMethodError
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.lambda$invoke$0(ProtocolFilterWrapper.java:101)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1$$Lambda$1177/1199784844.accept(Unknown Source)
	at org.apache.dubbo.rpc.AsyncRpcResult.lambda$whenCompleteWithContext$0(AsyncRpcResult.java:193)
	at org.apache.dubbo.rpc.AsyncRpcResult$$Lambda$1178/1622795726.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	... 26 more

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_45]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1907) ~[?:1.8.0_45]
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:177) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:61) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.5.jar:2.7.5]
	at com.alibaba.csp.sentinel.adapter.dubbo.SentinelDubboConsumerFilter.invoke(SentinelDubboConsumerFilter.java:75) ~[sentinel-apache-dubbo-adapter-1.7.1.jar:?]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at com.alibaba.csp.sentinel.adapter.dubbo.DubboAppContextFilter.invoke(DubboAppContextFilter.java:41) ~[sentinel-apache-dubbo-adapter-1.7.1.jar:?]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:49) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:55) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82) ~[dubbo-2.7.5.jar:2.7.5]
	... 94 more

**Comment by sczyh30** [comment]
Duplicate with #1231
