### ISSUE TITLE
异步方式无法block

### ISSUE THREAD

**Issue by cjdxhjj** [alibaba/Sentinel#1401]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
SphU.asyncEntry 接口无法block

### Describe what you expected to happen
我写了个服务接口，delay 1秒
![image](https://user-images.githubusercontent.com/5616997/79119717-9fb8bb00-7dc3-11ea-9792-617bfff96e69.png)
使用如下的方法测试，资源设置50ms超时，时间窗口2秒
![image](https://user-images.githubusercontent.com/5616997/79119772-ba8b2f80-7dc3-11ea-9b89-fbbd2a7ac6c3.png)

日志显示
没有请求block，所有请求都成功到达后端
![image](https://user-images.githubusercontent.com/5616997/79119916-12299b00-7dc4-11ea-972b-9ce1ee0936df.png)

### How to reproduce it (as minimally and precisely as possible)

1. 写一个缓慢的服务端，我采用delay 1秒模拟
2.  使用webflux webclient 请求服务，订阅里close AsyncEntry
3. 循环调用多次，我测试是调用100次

### Tell us your environment
jdk 14, kotlin 1.3.71, win 10 64 bit

**Comment by wavesZh** [comment]
你接口的延时时间太长了，你试试60ms，并且你每个请求间sleep 5ms 试试。

**Comment by cjdxhjj** [comment]
1秒的接口延时应该还算合理，我在调用处加了sleep依然没有block住

**Comment by sczyh30** [comment]
参考文档看看是否满足触发条件：https://github.com/alibaba/Sentinel/wiki/熔断降级
1.8.0 版本会对 RT 模式进行改进

**Comment by cjdxhjj** [comment]
我觉得使用thread local的方式有问题，使用协程，多个方法可能走到同一个线程

**Comment by cjdxhjj** [comment]
同样配置异步的不触发熔断，所有请求都会发送到后端，同步请求触发熔断，所以应该不是配置的问题，我的配置如下
      resource: zlw-get-user-pig-factory-list-api
      count: 100.0
      timeWindow: 2

**Comment by cjdxhjj** [comment]
kotlin和reactor都有一套context,spring 通过判断类型来决定使用同步的thread local或者使用异步的XXXContext
https://spring.io/blog/2019/05/16/reactive-transactions-with-spring

**Comment by cjdxhjj** [comment]
可以先提供一个版本的么，同步的或异步的都行，可以手工传入context
目前同步可以熔断，但是因为协程thread local出问题，导致一直狂刷错误日志
异步目前根本不能熔断

**Comment by sczyh30** [comment]
有什么问题 错误 具体描述下。

**Comment by cjdxhjj** [comment]
目前使用kotlin协程，同步方法一直报错
![image](https://user-images.githubusercontent.com/5616997/82627543-31b2af80-9c1d-11ea-8fad-8bf4dbcdacb9.png)
****

**Comment by cjdxhjj** [comment]
异步版本的上面有描述，不会触发

**Comment by sczyh30** [comment]
可否给个 demo 工程，社区来复现下

**Comment by cjdxhjj** [comment]
好的

**Comment by cjdxhjj** [comment]
我的测试工程地址在https://github.com/cjdxhjj/sentinel-demo.git

**Comment by cjdxhjj** [comment]
测试前先把web跑起来，bootRun
然后执行测试，一共写了5个测试,每个测试熔断策略都一致，分别跑500次
测试1，2使用sentinel同步api
测试3，4，5使用异步api

测试 1调用了三个接口，2个接口使用withContext异步调用，一个接口异步调用，出现少量熔断，大部分请求都通过，出现部分下列错误

> com.alibaba.csp.sentinel.ErrorEntryFreeException: The order of entry exit can't be paired with the order of entry, current entry in context: <test1>, but expected: <test2>
	at com.alibaba.csp.sentinel.CtEntry.exitForContext(CtEntry.java:80)
	at com.alibaba.csp.sentinel.CtEntry.trueExit(CtEntry.java:108)
	at com.alibaba.csp.sentinel.CtEntry.exit(CtEntry.java:61)
	at com.alibaba.csp.sentinel.Entry.exit(Entry.java:79)
	at com.alibaba.csp.sentinel.Entry.close(Entry.java:93)
	at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:56)
	at com.example.sentineldemo.shared.PrefExtensionKt.sentinel(PrefExtension.kt:6)
	at com.example.sentineldemo.shared.PrefExtensionKt$sentinel$1.invokeSuspend(PrefExtension.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by cjdxhjj** [comment]
测试2 删除了第三个请求，二个请求在withContext里异步执行， 绝大多数请求都被熔断了

**Comment by cjdxhjj** [comment]
测试3使用异步方式调用了一个接口，前面几个成功外，其它调用全熔断了
![image](https://user-images.githubusercontent.com/5616997/82652917-047ff480-9c51-11ea-82a8-fc5d04a5431a.png)

**Comment by cjdxhjj** [comment]
测试4没有使用协程，使用reactor,使用订阅来关闭context,前面成功，中间一部分熔断，后续请求都成功，请看sentinel-demo-clienttest4.log

**Comment by cjdxhjj** [comment]
测试5使用协程在withcontext里异步调用二个接口，前面几个请求成功，后面全失败

**Comment by cjdxhjj** [comment]
感觉每次换个姿势，结果都不同，现在服务器上使用的同步的方式，经常爆释放context的异常

![image](https://user-images.githubusercontent.com/5616997/82653570-ff6f7500-9c51-11ea-8be1-e2ed445a4912.png)

![image](https://user-images.githubusercontent.com/5616997/82653815-5c6b2b00-9c52-11ea-8bb8-091d6cd33944.png)

**Comment by cjdxhjj** [comment]
问题复现了么？昨天线上发生重大故障，外部的接口很慢，导致服务受到较大影响
