### ISSUE TITLE
Invalid character found in method name. HTTP method names must be tokens

### ISSUE THREAD

**Issue by yangxueyong** [alibaba/Sentinel#1408]
I pulled up the latest code for Sentinel,
When I start the three sentinel-demo-cluster-embedded (start the ClusterDemoApplication, All three machines are linked to the same nacos)

node1：server.port=7718  csp.sentinel.api.port=8723
node2：server.port=7719  csp.sentinel.api.port=8729
node3：server.port=7720  csp.sentinel.api.port=8727

Then I configured it in nacos:
[{"clientSet":["192.168.56.1@8723","192.168.56.1@8727"],"ip":"192.168.56.1","machineId":"192.168.56.1@8729","port":7719}]

At this point I noticed that node2's console was reporting an error:

```
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:428) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

How can I fix this mistake?  
	
Code environment:
sentinel-demo-cluster-embedded 1.8.0
nacos 1.2.0

**Comment by eniccay** [comment]
did u dound a solution?????

**Comment by UlissesJr** [comment]
HTTPS to http?

**Comment by eniccay** [comment]
@UlissesJr  it s https :)
