### ISSUE TITLE
Dashbord 同一个服务instance个数问题

### ISSUE THREAD

**Issue by myc547** [alibaba/Sentinel#1540]
env：dashboard version 1.7.2 部署到kubernetes下，A服务部署到kubernetes
A服务接入sentinel，并且部署2个instance（ip分别为：10.12.1.2,10.12.1.3），查看sentinel-dashboard，A服务的instance数量，sentinel-dashboard日志都正常。
当A服务通过kubernetes滚动升级后，也是两个instance，此时的ip分别为10.12.1.10，10.12.1.13，此时登陆sentinel-dashboard，发现A服务的instance变成4个，sentinel-dashboard日志一直扫描未升级前的A服务ip地址。
 ERROR 1 --- [pool-2-thread-1] c.a.c.s.dashboard.metric.MetricFetcher   : fetch metric http://10.12.1.2:8719/metric?startTime=1591965175000&endTime=1591965181000&refetch=false error

java.net.NoRouteToHostException: Host is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_212]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_212]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) [httpcore-nio-4.4.6.jar!/:4.4.6]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) [httpcore-nio-4.4.6.jar!/:4.4.6]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) [httpcore-nio-4.4.6.jar!/:4.4.6]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194) [httpasyncclient-4.1.3.jar!/:4.1.3]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.3.jar!/:4.1.3]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

**Comment by cdfive** [comment]
距离最近心跳时间超过指定时间(毫秒)是否自动删除失联节点，默认关闭
`-Dsentinel.dashboard.autoRemoveMachineMillis= 300000` 

可通过配置此参数，当对应ip的实例和控制台超时时间失联后会自动剔除，当剔除后在控制台查看instance以及抓取metric日志应该没问题，都是健康的实例。

参考：[https://github.com/alibaba/Sentinel/wiki/控制台#控制台配置项](https://github.com/alibaba/Sentinel/wiki/控制台#控制台配置项)
