### ISSUE TITLE
Failed to initialize Sentinel, ClassNotFoundException: com.alibaba.csp.sentinel.log.LoggerSpiProvider

### ISSUE THREAD

**Issue by BreadKid** [alibaba/Sentinel#1556]
own application console error
```
Error: failed to initialize Sentinel CommandCenterLog
java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/log/LoggerSpiProvider
	at com.alibaba.csp.sentinel.transport.log.CommandCenterLog.<clinit>(CommandCenterLog.java:36)
	at com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter$2.run(SimpleHttpCommandCenter.java:104)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.alibaba.csp.sentinel.log.LoggerSpiProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more
Exception in thread "Thread-264" java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/log/Logger
	at com.alibaba.csp.sentinel.transport.log.CommandCenterLog.info(CommandCenterLog.java:48)
	at com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter$2.run(SimpleHttpCommandCenter.java:104)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.alibaba.csp.sentinel.log.Logger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more
```
 and there is no such application on local sentinel dashboard

**Comment by cdfive** [comment]
`LoggerSpiProvider` is supported since 1.7.2, which version of Sentinel is used in your project?
Pay attention to Keep the dependent versions of sentinel consistent, 
`sentinel-core`,`sentinel-transport-common`... all use version 1.7.2.

**Comment by sczyh30** [comment]
> Pay attention to Keep the dependent versions of sentinel consistent, `sentinel-core`,`sentinel-transport-common`... all use version 1.7.2.

Yes, especially when you're using Spring Cloud Alibaba Sentinel.
