### ISSUE TITLE
Flaky test cases in sentinel-demo-quarkus module

### ISSUE THREAD

**Issue by sczyh30** [alibaba/Sentinel#1623]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

Flaky unstable test in `com.alibaba.csp.sentinel.demo.quarkus.GreetingResourceTest.testSentinelJaxRsQuarkusAdapter`:

```
ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.589 s <<< FAILURE! - in com.alibaba.csp.sentinel.demo.quarkus.GreetingResourceTest
[ERROR] testSentinelJaxRsQuarkusAdapter  Time elapsed: 1.048 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <429> but was <200>.

	at com.alibaba.csp.sentinel.demo.quarkus.GreetingResourceTest.testSentinelJaxRsQuarkusAdapter(GreetingResourceTest.java:45)

2020-07-22 03:10:31,055 INFO  [io.quarkus] (main) Quarkus stopped in 0.027s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   GreetingResourceTest.testSentinelJaxRsQuarkusAdapter:45 1 expectation failed.
Expected status code <429> but was <200>.
```

https://app.circleci.com/pipelines/github/alibaba/Sentinel/264/workflows/fd9ae813-fef6-416c-8a0d-65c55b95275d/jobs/2093

### Describe what you expected to happen

The test case should not fail.

**Comment by JiangZian** [comment]
I will finished this issue

**Comment by sczyh30** [comment]
New observed in https://travis-ci.org/github/alibaba/Sentinel/jobs/712409015:

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.589 s <<< FAILURE! - in com.alibaba.csp.sentinel.demo.quarkus.GreetingResourceTest
[ERROR] testSentinelAnnotationQuarkusAdapter  Time elapsed: 2.316 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: is "globalBlockHandler, ex:null"
  Actual: globalDefaultFallback, ex:test sentinel fallback
	at com.alibaba.csp.sentinel.demo.quarkus.GreetingResourceTest.testSentinelAnnotationQuarkusAdapter(GreetingResourceTest.java:70)
2020-07-28 02:35:11,394 INFO  [io.quarkus] (main) Quarkus stopped in 0.048s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   GreetingResourceTest.testSentinelAnnotationQuarkusAdapter:70 1 expectation failed.
Response body doesn't match expectation.
Expected: is "globalBlockHandler, ex:null"
  Actual: globalDefaultFallback, ex:test sentinel fallback
```
