### ISSUE TITLE
启动sentinel-dashboard  一直卡住，jstack日志如下

### ISSUE THREAD

**Issue by keybersan** [alibaba/Sentinel#1635]
2020-07-28 12:21:28
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode):

"sentinel-heartbeat-send-task-thread-2" #19 daemon prio=5 os_prio=0 tid=0x000000001bad6800 nid=0x3858 waiting on condition [0x000000001f17e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000701f6cf78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"sentinel-time-tick-thread" #18 daemon prio=5 os_prio=0 tid=0x000000001b0f8800 nid=0x2c10 waiting on condition [0x000000001c12f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at java.lang.Thread.sleep(Unknown Source)
        at java.util.concurrent.TimeUnit.sleep(Unknown Source)
        at com.alibaba.csp.sentinel.util.TimeUtil$1.run(TimeUtil.java:37)
        at java.lang.Thread.run(Unknown Source)

"DestroyJavaVM" #17 prio=5 os_prio=0 tid=0x0000000002800800 nid=0x3bd4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"sentinel-heartbeat-send-task-thread-1" #15 daemon prio=5 os_prio=0 tid=0x000000001c5a8000 nid=0x734 waiting on condition [0x000000001d1ff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000701f6cf78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"sentinel-command-center-executor-thread-1" #14 prio=5 os_prio=0 tid=0x000000001be29800 nid=0x262c runnable [0x000000001d3af000]
   java.lang.Thread.State: RUNNABLE
        at java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
        at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
        at java.net.PlainSocketImpl.accept(Unknown Source)
        - locked <0x0000000701f890f8> (a java.net.SocksSocketImpl)
        at java.net.ServerSocket.implAccept(Unknown Source)
        at java.net.ServerSocket.accept(Unknown Source)
        at com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter$ServerThread.run(SimpleHttpCommandCenter.java:188)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00000000199ce000 nid=0x7ac runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000000019991800 nid=0x8d8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x000000001998a800 nid=0x382c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x0000000019987800 nid=0x3bfc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x0000000019986800 nid=0x3bf8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000001ad73800 nid=0x3bf4 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000028fb800 nid=0x3bf0 in Object.wait() [0x000000001acce000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000701fb8be0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        - locked <0x0000000701fb8be0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000028f1000 nid=0x3bec in Object.wait() [0x000000001abcf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000701f942a8> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        - locked <0x0000000701f942a8> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"VM Thread" os_prio=2 tid=0x0000000019938000 nid=0x3be8 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002816800 nid=0x3bd8 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002818000 nid=0x3bdc runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002819800 nid=0x3be0 runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x000000000281b000 nid=0x3be4 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x000000001ae04800 nid=0x16f4 waiting on condition

JNI global references: 518

**Comment by lawrencewu** [comment]
Can you please post the CPU and Memory usage.
Is the disk full ?

**Comment by keybersan** [comment]
> Can you please post the CPU and Memory usage.
> Is the disk full ?
![sentinel](https://user-images.githubusercontent.com/27944820/88780937-4a5fb880-d1be-11ea-8d17-bd6f1197b8cd.png)

**Comment by TwoWaterLee** [comment]
@keybersan 
 这个bug解决了吗？
 使用最新版本的 sentinel-dashboard 是否可以正常启动呢？

**Comment by TwoWaterLee** [comment]
@keybersan @lawrencewu 

如果你指的 “启动sentinel-dashboard 一直卡住”，是指无法看到界面，如下图所示，那么我应该是重现了这个bug。

![image](https://user-images.githubusercontent.com/9162128/103201808-cd329e00-492b-11eb-8d3a-8b76b7fc64ad.png)

其实这是一个前端错误导致的bug，实际上，后台的API是可以正常访问的。我使用 `postman` 测试如下：

![image](https://user-images.githubusercontent.com/9162128/103201878-fc490f80-492b-11eb-928b-4bf961d46b53.png)


同时，升级到最新版本， 这个前端bug也不存在了，我本地启动一切正常。具体是哪个版本修复的，我没有测试。

所以，我认为这个 issue 可以关闭了。
