### ISSUE TITLE
failed to initialize Sentinel CommandCenterLog and Command server port not initialized, won't send heartbeat

### ISSUE THREAD

**Issue by yosamaru** [alibaba/Sentinel#1715]
idea run  throw excetption and Command server port not initialized, won't send heartbeat

```
Error: failed to initialize Sentinel CommandCenterLog
java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/log/LoggerSpiProvider
	at com.alibaba.csp.sentinel.transport.log.CommandCenterLog.<clinit>(CommandCenterLog.java:36)
	at com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter$2.run(SimpleHttpCommandCenter.java:104)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.alibaba.csp.sentinel.log.LoggerSpiProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
Exception in thread "Thread-492" java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/log/Logger
	at com.alibaba.csp.sentinel.transport.log.CommandCenterLog.info(CommandCenterLog.java:48)
	at com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter$2.run(SimpleHttpCommandCenter.java:104)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.alibaba.csp.sentinel.log.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

this is config：

sentinel.properties

```
project.name=kassadin-admin
csp.sentinel.dashboard.server=localhost:8858
csp.sentinel.heartbeat.interval.ms=20
csp.sentinel.api.port=8720
csp.sentinel.metric.file.single.size=52428800
csp.sentinel.metric.file.total.count=6
csp.sentinel.log.use.pid=true
csp.sentinel.log.output.type=console
```

Application.yml 

```yaml
spring:                                            
  application:                                     
    name: kassadin-admin                           
  cloud:                                           
    nacos:                                         
      discovery:                                   
        server-addr: localhost:8848                
      config:                                      
        server-addr: localhost:8848                
        file-extension: yaml                       
    sentinel:                                      
      transport:                                   
        dashboard: localhost:8858                  
        port: 8820                                 
      eager: true                                  
      datasource:                                  
        kaasadin:                                  
          nacos:                                   
            server-addr: http://localhost:8848     
            dataId: "KASSADIN_ADMIN_RULES"         
            groupId: "SENTINEL_GROUP"              
            rule-type: flow
```

i hope you help me, thank you.

**Comment by sczyh30** [comment]
If you're using Spring Cloud Alibaba, be sure to keep version of all Sentinel dependencies consistent. See [FAQ](https://github.com/alibaba/Sentinel/wiki/FAQ#q-%E5%BC%95%E4%BA%86-spring-cloud-alibaba-%E7%9A%84%E7%9B%B8%E5%85%B3%E4%BE%9D%E8%B5%96%E4%BB%A5%E5%90%8E%E5%86%8D%E5%BC%95%E9%AB%98%E7%89%88%E6%9C%AC%E7%9A%84-sentinel-%E4%BE%9D%E8%B5%96%E4%BC%9A%E6%8A%A5%E9%94%99) for more information.

**Comment by yosamaru** [comment]
ok, thank you for your reply

**Comment by yosamaru** [comment]
ok, thank you for your replyok, thank you for your reply
