### ISSUE TITLE
Could not initialize class com.alibaba.csp.sentinel.context.ContextUtil

### ISSUE THREAD

**Issue by a419506442** [alibaba/Sentinel#1763]
## Issue Description

java.lang.NullPointerException: null 
	at com.alibaba.csp.sentinel.log.DateFileLogHandler.publish(DateFileLogHandler.java:83) 
	at java.util.logging.Logger.log(Logger.java:738) 
	at java.util.logging.Logger.doLog(Logger.java:765) 
	at java.util.logging.Logger.log(Logger.java:851) 
	at com.alibaba.csp.sentinel.log.LogBase.log(LogBase.java:158) 
	at com.alibaba.csp.sentinel.log.RecordLog.info(RecordLog.java:37) 
	at com.alibaba.csp.sentinel.node.DefaultNode.addChild(DefaultNode.java:94) 
	at com.alibaba.csp.sentinel.context.ContextUtil.initDefaultContext(ContextUtil.java:68) 
	at com.alibaba.csp.sentinel.context.ContextUtil.<clinit>(ContextUtil.java:62) 
	at com.alibaba.csp.sentinel.adapter.spring.webmvc.AbstractSentinelInterceptor.preHandle(AbstractSentinelInterceptor.java:62) 
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:141) 
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1035) 
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) 
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) 
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) 
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) 
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at com.moggy.logs.filter.LogMDCFilter.doFilter(LogMDCFilter.java:31) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at com.moggy.common.security.web.xss.XSSFilter.doFilter(XSSFilter.java:22) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209) 
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) 
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) 
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) 
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) 
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:141) 
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109) 
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) 
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) 
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) 
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) 
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) 
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) 
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) 
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) 
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) 
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) 
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
	at java.lang.Thread.run(Thread.java:745) 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

环境问题吧， 本地都很正常，生产docker

**Comment by sczyh30** [comment]
Please check whether the process has the write permission for directory `~/logs/csp`.

**Comment by sczyh30** [comment]
Any feedback?

**Comment by 760374564** [comment]
Any exceptions to this code from the console? Exceptions caught here are not output to the log file and can only be viewed from the console. For example, my problem is that the disk is full and the FileHandler cannot be created.
 code in DateFileLogHandler:

   private void rotateDate() {
         .....

        try {
            this.handler = new FileHandler(newPattern, limit, count, append);  //FileHandler cannot be created when disk is full
            if (initialized) {
                handler.setEncoding(this.getEncoding());
                handler.setErrorManager(this.getErrorManager());
                handler.setFilter(this.getFilter());
                handler.setFormatter(this.getFormatter());
                handler.setLevel(this.getLevel());
            }
        } catch (SecurityException e) {
            e.printStackTrace();   //  Exception can only be viewed from the console here
        } catch (IOException e) {
            e.printStackTrace();   //  Exception can only be viewed from the console here
        }
    }

**Comment by 760374564** [comment]
Any exceptions to this code from the console? Exceptions caught here are not output to the log file and can only be viewed from the console. For example, my problem is that the disk is full and the FileHandler cannot be created.
 code in DateFileLogHandler:

   private void rotateDate() {
         .....

        try {
            this.handler = new FileHandler(newPattern, limit, count, append);  //FileHandler cannot be created when disk is full
            if (initialized) {
                handler.setEncoding(this.getEncoding());
                handler.setErrorManager(this.getErrorManager());
                handler.setFilter(this.getFilter());
                handler.setFormatter(this.getFormatter());
                handler.setLevel(this.getLevel());
            }
        } catch (SecurityException e) {
            e.printStackTrace();   //  Exception can only be viewed from the console here
        } catch (IOException e) {
            e.printStackTrace();   //  Exception can only be viewed from the console here
        }
    }
