### ISSUE TITLE
启动springboot服务一直报npe，是跟日志有关？

### ISSUE THREAD

**Issue by JerryJavaCoding** [alibaba/Sentinel#186]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sentinelConfiguration': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:423)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$127/452364286.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
        at com.yy.llb.mgr.MgrApplication.main(MgrApplication.java:18)
Caused by: java.lang.ExceptionInInitializerError: null
        at com.yy.llb.mgr.config.SentinelConfiguration.init(SentinelConfiguration.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:369)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:312)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
        ... 17 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.alibaba.csp.sentinel.log.DateFileLogHandler.publish(DateFileLogHandler.java:75)
        at java.util.logging.Logger.log(Logger.java:738)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at com.alibaba.csp.sentinel.log.RecordLog.info(RecordLog.java:46)
        at com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager$FlowPropertyListener.configLoad(FlowRuleManager.java:200)
        at com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager$FlowPropertyListener.configLoad(FlowRuleManager.java:181)
        at com.alibaba.csp.sentinel.property.DynamicSentinelProperty.addListener(DynamicSentinelProperty.java:40)
        at com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager.<clinit>(FlowRuleManager.java:63)
        ... 25 common frames omitted

**Comment by sczyh30** [comment]
Hi, please follow the [issue template](https://github.com/alibaba/Sentinel/blob/master/.github/ISSUE_TEMPLATE.md) to tell us more information (e.g. your environment, your configuration).

**Comment by JerryJavaCoding** [comment]
user.home指定路径权限问题
