### ISSUE TITLE
Using npm run build in sentinel-dashboard failed 

### ISSUE THREAD

**Issue by ITGcx** [alibaba/Sentinel#1894]
1.运行npm install 
警告
npm WARN bootstrap-switch@3.3.4 requires a peer of bootstrap@^3.1.1 but none was installed.
npm WARN sentinel-dashboard@1.0.0 No repository field.
2.运行npm run build
报错
app/scripts/services/flow_service_v1.js: line 18, col 13, 'param' is defined but never used.
app/scripts/services/flow_service_v1.js: line 95, col 29, Expected '===' and instead saw '=='.
app/scripts/services/flow_service_v1.js: line 95, col 51, Expected '===' and instead saw '=='.
app/scripts/services/flow_service_v1.js: line 96, col 70, Expected '===' and instead saw '=='.
app/scripts/services/flow_service_v1.js: line 105, col 36, Expected '===' and instead saw '=='.
app/scripts/services/flow_service_v1.js: line 109, col 36, Expected '===' and instead saw '=='.
app/scripts/services/flow_service_v1.js: line 113, col 119, Line is too long.
app/scripts/services/flow_service_v1.js: line 74, col 14, 'notNumberAtLeastZero' is defined but never used.
app/scripts/services/flow_service_v1.js: line 84, col 13, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 88, col 13, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 92, col 13, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 97, col 17, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 102, col 13, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 106, col 13, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 110, col 13, 'alert' is not defined.
app/scripts/services/flow_service_v1.js: line 114, col 13, 'alert' is not defined.

node 版本：v7.0.0
npm:版本:3.10.8

![WX20201211-122548](https://user-images.githubusercontent.com/15756567/101861882-1654c500-3bac-11eb-9235-5d99aa7b70df.png)

**Comment by RickJou** [comment]
遇到了一样的问题,怎么解决呢?

**Comment by cdfive** [comment]
打印的warn、error不影响使用的，执行`npm run build`后，
运行`com.alibaba.csp.sentinel.dashboard`包下的`DashboardApplication`类, 
然后访问：
[http://localhost:8080/index_dev.htm](http://localhost:8080/index_dev.htm) 或者
[http://localhost:8080/index.htm](http://localhost:8080/index.htm)就好。

当修改页面或者js后，点击菜单->Build->Build Module 'sentinel-dashboard'，然后刷新页面就行。

用master分支刚试了没问题，步骤如上供参考。

**Comment by mhhxyt** [comment]
sentinel-dashboard 版本 1.8.2 

node:   v8.11.2  npm:  5.6.0
或
node:  v14.17.6 npm:   6.14.15

registry:    https://registry.npm.taobao.org

运行 npm run build命令：

> gulp build

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (resources\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (resources\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (resources\gulpfile.js:115:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requireOrImport (resources\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sentinel-dashboard@1.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentinel-dashboard@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:


请问这个问题在哪里 ？

**Comment by mhhxyt** [comment]
node.js 版本 v8.11.2
npm版本 5.6.0
#npm install -g gulp@3.9.1  --no-fund
#npm install  --no-fund
# gulp -v
    [16:45:56] CLI version 3.9.1
   [16:45:56] Local version 3.9.1

#npm run build
#npm start
