### ISSUE TITLE
1.8.0 ZookeeperDataSource do not support dubbo zk cluster address

### ISSUE THREAD

**Issue by adeng-wc** [alibaba/Sentinel#1903]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

support zookeeper address: "10.90.8.7:2631?backup=10.90.8.99:2631,10.90.8.100:2631";

### How to reproduce it (as minimally and precisely as possible)

Demo :

String remoteAddress = "10.90.8.7:2631?backup=10.90.8.99:2631,10.90.8.100:2631";
        ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new ZookeeperDataSource<>(remoteAddress, path,
                source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
                }));

### Tell us your environment

<artifactId>sentinel-datasource-zookeeper</artifactId>
<version>1.8.0</version>

**Comment by adeng-wc** [comment]
[2020-12-16 16:54:18] [main] INFO org.apache.zookeeper.ZooKeeper [T:] Initiating client connection, connectString=10.90.8.7:2631?backup=10.90.8.99:
2631,10.90.8.100:2631 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@6c4980d3
[2020-12-16 16:54:18] [main] ERROR o.a.c.f.imps.CuratorFrameworkImpl [T:] Background exception was not retry-able or retry gave up
java.net.UnknownHostException: 10.90.8.7:2631?backup=10.90.8.99: invalid IPv6 address
        at java.net.InetAddress.getAllByName(InetAddress.java:1170)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
        at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:150)
        at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94)
        at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55)
        at org.apache.curator.ConnectionState.reset(ConnectionState.java:262)
        at org.apache.curator.ConnectionState.start(ConnectionState.java:109)
        at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:191)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:259)
        at com.alibaba.csp.sentinel.datasource.zookeeper.ZookeeperDataSource.initZookeeperListener(ZookeeperDataSource.java:140)
        at com.alibaba.csp.sentinel.datasource.zookeeper.ZookeeperDataSource.init(ZookeeperDataSource.java:88)
        at com.alibaba.csp.sentinel.datasource.zookeeper.ZookeeperDataSource.<init>(ZookeeperDataSource.java:56)
        at com.netease.nft.tickets.common.configuration.SentinelConfiguration.loadRulesFromZkDataSource(SentinelConfiguration.java:58)
        at com.netease.nft.tickets.common.configuration.SentinelConfiguration.<clinit>(SentinelConfiguration.java:29)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:467)
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
        at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
        at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
        at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:138)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:110)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:
393)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:249)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.
java:281)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.
java:125)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
        at com.netease.MainApplication.main(MainApplication.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by brothelul** [comment]
@adeng-wc it seems not cause by  the sentinel-datasource-zookeeper, Zookeeper support the cluster url the example you provided "10.90.8.7:2631?backup=10.90.8.99:2631,10.90.8.100:2631". the real cause is happened in java.net.InetAddress#getAllByName(java.lang.String, java.net.InetAddress) the code like below
![image](https://user-images.githubusercontent.com/25661357/102375689-c2a80880-3ffd-11eb-8a46-c857c9eb5bf2.png)
It look like the IPV6  address has some problem. do you have any idea about this? @cdfive @sczyh30

**Comment by brothelul** [comment]
@adeng-wc this feature is already in Zookeeper, Zookeeper support the cluster url which you provided  `10.90.8.7:2631?backup=10.90.8.99:2631,10.90.8.100:2631` after version 3.4.12(not include). 
the code in version 3.4.12
![image](https://user-images.githubusercontent.com/25661357/102438724-d1230e00-4057-11eb-82e9-af64e5494683.png)
the marked place will encounter the problem you provided: java.net.UnknownHostException: 10.90.8.7:2631?backup=10.90.8.99: invalid IPv6 address
the code in version 3.4.13 and later
![image](https://user-images.githubusercontent.com/25661357/102438884-22cb9880-4058-11eb-95b5-57fe4c9bb468.png)
it catch the UnknownHostException and return the original host.
you can check if your project has the old version Zookeeper, and exclude it. I think this way can solve the problem you encounter. Do you have any idea about this? @cdfive @sczyh30

**Comment by 799983050** [comment]
你也在做sentinel1.8.0，zk规则的持久化改造吗？加个qq交流下吧：799983050

**Comment by adeng-wc** [comment]
> 你也在做sentinel1.8.0，zk规则的持久化改造吗？加个qq交流下吧：799983050

很久不用QQ了，账号密码都已经忘记了。新项目打算使用 sentinel1.8.0，正在做持久化改造。

**Comment by 799983050** [comment]
哦哦，你的项目也是dubbo+zk吗？如果是的话，加个qq交流下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "阿登灯"<notifications@github.com&gt;; 
发送时间: 2020年12月28日(星期一) 上午10:06
收件人: "alibaba/Sentinel"<Sentinel@noreply.github.com&gt;; 
抄送: "陈伟"<799983050@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/Sentinel] 1.8.0 ZookeeperDataSource do not support dubbo zk cluster address (#1903)





  
你也在做sentinel1.8.0，zk规则的持久化改造吗？加个qq交流下吧：799983050
  
很久不用QQ了，账号密码都已经忘记了。新项目打算使用 sentinel1.8.0，正在做持久化改造。

**Comment by adeng-wc** [comment]
> @adeng-wc this feature is already in Zookeeper, Zookeeper support the cluster url which you provided `10.90.8.7:2631?backup=10.90.8.99:2631,10.90.8.100:2631` after version 3.4.12(not include).
> the code in version 3.4.12
> ![image](https://user-images.githubusercontent.com/25661357/102438724-d1230e00-4057-11eb-82e9-af64e5494683.png)
> the marked place will encounter the problem you provided: java.net.UnknownHostException: 10.90.8.7:2631?backup=10.90.8.99: invalid IPv6 address
> the code in version 3.4.13 and later
> ![image](https://user-images.githubusercontent.com/25661357/102438884-22cb9880-4058-11eb-95b5-57fe4c9bb468.png)
> it catch the UnknownHostException and return the original host.
> you can check if your project has the old version Zookeeper, and exclude it. I think this way can solve the problem you encounter. Do you have any idea about this? @cdfive @sczyh30

The 3.4.14 version of zk solves this problem。

**Comment by Lin-Liang** [comment]
hey, will you try "10.90.8.7:2631,10.90.8.99:2631,10.90.8.100:2631"  to see what is going on?

**Comment by sczyh30** [comment]
Any further feedback?
