### ISSUE TITLE
sentinel 1.8.0 导致openfeign接口出现BeanCurrentlyInCreationException

### ISSUE THREAD

**Issue by yangxiufeng666** [alibaba/Sentinel#2065]
### Describe what happened (or what feature you want)

当设置feign.sentinel.enabled: true时出现如下错误
```
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'com.example.demo.ProviderFacade': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:355) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:227) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at com.alibaba.cloud.sentinel.feign.SentinelFeign$Builder$1.create(SentinelFeign.java:84) ~[spring-cloud-starter-alibaba-sentinel-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:64) ~[feign-core-10.10.1.jar:na]
	at feign.Feign$Builder.target(Feign.java:269) ~[feign-core-10.10.1.jar:na]
	at org.springframework.cloud.openfeign.HystrixTargeter.target(HystrixTargeter.java:38) ~[spring-cloud-openfeign-core-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:338) ~[spring-cloud-openfeign-core-2.2.7.RELEASE.jar:2.2.7.RELEASE]
```

当设置feign.sentinel.enabled: false，这feign接口无问题， 但是这不就用不了sentinel了吗

### Describe what you expected to happen
简单的demo如下：
1. ConsumerController
`@RestController
public class ConsumerController {
    @Autowired
    private ProviderFacade providerFacade;

    @GetMapping("getProviderPort")
    public String getProviderPort(){
        return providerFacade.getPort();
    }`
2. ProviderFacade
`@FeignClient(name = "sentinel-provider" , fallbackFactory = ProviderFacadeFallbackFactory.class)
public interface ProviderFacade {
    @GetMapping("getPort")
    String getPort();

}`

### Tell us your environment
 <spring-boot.version>2.3.7.RELEASE</spring-boot.version>
 <spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>

**Comment by yangxiufeng666** [comment]
问题找到， 不是sentinel的问题，我把spring-cloud版本降到Hoxton.SR9 及以下就不会出现这个问题， 我升级到Hoxton.SR10立马出现这个问题。

**Comment by GodLiang** [comment]
我也碰到这个问题了。我在想是Sentinel的问题呢还是springcloud的问题呢。alibaba和cloud整合碰到过好几次坑了。

**Comment by lxc455735702** [comment]
我也遇到了这个问题，现在只能是降低spring-cloud版本降到Hoxton.SR9吗？还有其它解决方案吗

**Comment by lxc455735702** [comment]
1.8.3有修复吗？Hoxton.SR10

**Comment by wxy0724** [comment]
我目前SpringBoot2.7.16，Sentinel 1.8.5 也有这个问题，服务启动异常，抛错误如下：
Error creating bean with name 'qableCfgServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'com.fang.industry.api.quicktable.HouseCoreControllerApi': Requested bean is currently in creation: Is there an unresolvable circular reference?

并且没有 feign.sentinel.enabled 设置，我该如何处理呢？
