### ISSUE TITLE
Failed to send heartbeat (Connection refused) in Docker

### ISSUE THREAD

**Issue by wenhao** [alibaba/Sentinel#2233]
## Issue Description

在docker中无法启动。

日志如下：

2021-06-11 09:52:03 2021-06-11 09:52:03.434 INFO [SimpleHttpHeartbeatSender] Default console address list retrieved: [Endpoint{protocol=HTTP, host='localhost, port=8080}]
2021-06-11 09:52:03 2021-06-11 09:52:03.434 INFO [HeartbeatSenderProvider] HeartbeatSender activated: com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender
2021-06-11 09:52:03 2021-06-11 09:52:03.436 INFO [HeartbeatSenderInit] Heartbeat interval not configured in config property or invalid, using sender default: 10000
2021-06-11 09:52:03 2021-06-11 09:52:03.437 INFO [HeartbeatSenderInit] HeartbeatSender started: com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender
2021-06-11 09:52:03 2021-06-11 09:52:03.437 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc with order -1
2021-06-11 09:52:03 2021-06-11 09:52:03.439 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit with order 2147483647
2021-06-11 09:52:03 2021-06-11 09:52:03.440 INFO [InitExecutor] Executing com.alibaba.csp.sentinel.init.ParamFlowStatisticSlotCallbackInit with order 2147483647
2021-06-11 09:52:08 2021-06-11 09:52:08.457 WARNING [SimpleHttpHeartbeatSender] Failed to send heartbeat to Endpoint{protocol=HTTP, host='localhost, port=8080}
2021-06-11 09:52:08 java.net.ConnectException: Connection refused (Connection refused)
2021-06-11 09:52:08 	at java.net.PlainSocketImpl.socketConnect(Native Method)
2021-06-11 09:52:08 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
2021-06-11 09:52:08 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
2021-06-11 09:52:08 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
2021-06-11 09:52:08 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
2021-06-11 09:52:08 	at java.net.Socket.connect(Socket.java:606)
2021-06-11 09:52:08 	at com.alibaba.csp.sentinel.transport.heartbeat.client.SimpleHttpClient.request(SimpleHttpClient.java:98)
2021-06-11 09:52:08 	at com.alibaba.csp.sentinel.transport.heartbeat.client.SimpleHttpClient.post(SimpleHttpClient.java:82)
2021-06-11 09:52:08 	at com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender.sendHeartbeat(SimpleHttpHeartbeatSender.java:74)
2021-06-11 09:52:08 	at com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc$1.run(HeartbeatSenderInitFunc.java:91)
2021-06-11 09:52:08 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2021-06-11 09:52:08 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2021-06-11 09:52:08 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2021-06-11 09:52:08 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2021-06-11 09:52:08 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-06-11 09:52:08 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-06-11 09:52:08 	at java.lang.Thread.run(Thread.java:748)
2021-06-11 09:52:18 2021-06-11 09:52:18.437 WARNING [SimpleHttpHeartbeatSender] Failed to send heartbeat to Endpoint{protocol=HTTP, host='localhost, port=8080}
2021-06-11 09:52:18 java.net.ConnectException: Connection refused (Connection refused)
2021-06-11 09:52:18 	at java.net.PlainSocketImpl.socketConnect(Native Method)
2021-06-11 09:52:18 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
2021-06-11 09:52:18 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
2021-06-11 09:52:18 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
2021-06-11 09:52:18 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
2021-06-11 09:52:18 	at java.net.Socket.connect(Socket.java:606)
2021-06-11 09:52:18 	at com.alibaba.csp.sentinel.transport.heartbeat.client.SimpleHttpClient.request(SimpleHttpClient.java:98)
2021-06-11 09:52:18 	at com.alibaba.csp.sentinel.transport.heartbeat.client.SimpleHttpClient.post(SimpleHttpClient.java:82)
2021-06-11 09:52:18 	at com.alibaba.csp.sentinel.transport.heartbeat.SimpleHttpHeartbeatSender.sendHeartbeat(SimpleHttpHeartbeatSender.java:74)
2021-06-11 09:52:18 	at com.alibaba.csp.sentinel.transport.init.HeartbeatSenderInitFunc$1.run(HeartbeatSenderInitFunc.java:91)
2021-06-11 09:52:18 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2021-06-11 09:52:18 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2021-06-11 09:52:18 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2021-06-11 09:52:18 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2021-06-11 09:52:18 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-06-11 09:52:18 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-06-11 09:52:18 	at java.lang.Thread.run(Thread.java:748)

**Comment by sczyh30** [comment]
Please check the network between your service and the Sentinel dashboard.
