### ISSUE TITLE
GateWayRuleManager空指针错误

### ISSUE THREAD

**Issue by zhouyutong** [alibaba/Sentinel#2617]
## Issue Description

Type: *bug report* or *feature request*

### 哨兵控制台更新流控规则，网关在 更新规则时抛出空指针异常，更新失败。
java.lang.NullPointerException
	at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.applyToConvertedParamMap(GatewayRuleManager.java:230)
	at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.applyGatewayRuleInternal(GatewayRuleManager.java:200)
	at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.configUpdate(GatewayRuleManager.java:118)
	at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager$GatewayRulePropertyListener.configUpdate(GatewayRuleManager.java:114)
	at com.alibaba.csp.sentinel.property.DynamicSentinelProperty.updateValue(DynamicSentinelProperty.java:57)
	at com.alibaba.csp.sentinel.adapter.gateway.common.rule.GatewayRuleManager.loadRules(GatewayRuleManager.java:78)
	at com.alibaba.csp.sentinel.adapter.gateway.common.command.UpdateGatewayRuleCommandHandler.handle(UpdateGatewayRuleCommandHandler.java:59)
	at com.alibaba.csp.sentinel.transport.command.http.HttpEventTask.run(HttpEventTask.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### 这种情况如何规避才可更新成功

版本：
<dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>2.2.5.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.3.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by zhouyutong** [comment]
错误代码行：ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule);
哨兵控制白版本：1.8.3

**Comment by zhouyutong** [comment]
重现步骤：
1、重启gateway
2、更新哨兵控制台的流控规则 
3、gateway的UpdateGatewayRuleCommandHandler.hand接收请求，执行到GatewayRuleManager.java的230行：ParameterMetricStorage.getParamMetricForResource(resource).clearForRule(rule); 出现空指针。

错误原因：
因为是重启gateway后直接在哨兵控制台更新流控规则，此时还没有对规则对应的resource做任何调用之前，不会触发ParameterMetricStorage.initParamMetricsFor方法，因此ParameterMetricStorage.getParamMetricForResource(resource)必然返回null，从而导致空指针。

**Comment by sczyh30** [comment]
This has been fixed in 1.8.1 via #1729. Please check whether the actual Sentinel version >= 1.8.1.
