### ISSUE TITLE
spring cloud gateway sentinel 熔断规则不生效

### ISSUE THREAD

**Issue by lijunyong** [alibaba/Sentinel#2758]
通过spring cloud gateway转发demo项目，我设置了熔断规则，当停止demo项目，通过gateway请求多次没有直接返回而是调了后台应用，CircuitBreaker状态一直是CLOSE的
```
[
    {
        "resource": "demo",
        "limitApp": "default",
        "grade": 2,
        "count": 1.0,
        "timeWindow": 70,
        "minRequestAmount": 2,
        "slowRatioThreshold": 0.5,
        "statIntervalMs": 5000
    }
]
```
```
2022-06-24 10:23:05.740 ERROR 8276 --- [ctor-http-nio-5] a.w.r.e.AbstractErrorWebExceptionHandler : [07c1bd86-13]  500 Server Error for HTTP GET "/hello"

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:8081
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/hello" [ExceptionHandlingWebHandler]
Stack trace:
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_261]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715) ~[na:1.8.0_261]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]

```
![image](https://user-images.githubusercontent.com/14291793/175452311-a64f1c90-c2c8-40d4-90ac-257a33efd2f3.png)

**Comment by lijunyong** [comment]
![image](https://user-images.githubusercontent.com/14291793/175451925-7bd9c695-9736-4a09-8db1-efb96cf7abec.png)
