### ISSUE TITLE
Wrong state for SentinelResource annotation

### ISSUE THREAD

**Issue by beifuyiqiedeqilin** [alibaba/Sentinel#2766]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
when i try to apply SentinelResource on single method under FeignClient
```
@FeignClient(name = "local-remote-service", url = "http://127.0.0.1:8080/v2")
public interface RemoteService {
    @GetMapping("/hello")
    @SentinelResource(value = "testFail")
    String getWord();
}
```
then exception throw
```
java.lang.IllegalStateException: Wrong state for SentinelResource annotation
	at com.alibaba.csp.sentinel.annotation.aspectj.SentinelResourceAspect.invokeResourceWithSentinel(SentinelResourceAspect.java:49) ~[sentinel-annotation-aspectj-1.8.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_321]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_321]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_321]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_321]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.18.jar:5.3.18]
```
### Describe what you expected to happen
**does this solution can be supported?**

### Tell us your environment
```
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>2.2.8.RELEASE</version>
        </dependency>
```

### Anything else we need to know?
#74

**Comment by sczyh30** [comment]
Maybe similar to #284

**Comment by beifuyiqiedeqilin** [comment]
@sczyh30 Hi, So does have any conclusions of this? Since #284 was 2 years ago, it still exists.
