### ISSUE TITLE
[Bug]Metrics export error when resource name includes '*'

### ISSUE THREAD

**Issue by xiangtianyu** [alibaba/Sentinel#2989]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
```
      try (Entry entry = SphU.entry("*HelloWorld")) {
          // Your business logic here.
          System.out.println("hello world");
      } catch (BlockException e) {
          // Handle rejected request.
          e.printStackTrace();
      }
```
I declared a special resource name include '*', and then the metrics exporter will throw this exception

```
Caused by: java.lang.IllegalArgumentException: Repository: cannot add mbean for pattern name Sentinel:type=com.example.springdemo.SpringDemoApplication,name="*HelloWorld",classification="0"
        ... 18 more
2022-12-06 15:17:55.597 WARNING [JMX Metric Exporter] export to JMX MetricBean failed.
javax.management.RuntimeOperationsException
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:413)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.alibaba.csp.sentinel.metric.exporter.jmx.MBeanRegistry.register(MBeanRegistry.java:73)
        at com.alibaba.csp.sentinel.metric.exporter.jmx.MetricBeanWriter.write(MetricBeanWriter.java:81)
        at com.alibaba.csp.sentinel.metric.exporter.jmx.JMXMetricExporter.export(JMXMetricExporter.java:66)
        at com.alibaba.csp.sentinel.metric.exporter.jmx.JMXMetricExporter$JMXExportTask.run(JMXMetricExporter.java:82)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Repository: cannot add mbean for pattern name Sentinel:type=com.example.springdemo.SpringDemoApplication,name="*HelloWorld",classification="0"
        ... 18 more
2022-12-06 15:17:56.599 WARNING [JMX Metric Exporter] export to JMX MetricBean failed.
javax.management.RuntimeOperationsException
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:413)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
```

### How to reproduce it (as minimally and precisely as possible)

1. Create a resource name include '*' and you will reproduce

### Tell us your environment
macos system 
```
<dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>1.8.4</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-metric-exporter</artifactId>
            <version>1.8.4</version>
        </dependency>
```

**Comment by BlueSodaWater** [comment]
**Reason**
This is caused by objectName’s naming rules in JMX.Here are rules.

```
Here, domain is an arbitrary string.
If the domain is empty, it implies the default domain for the MBean Server where the Object Name is used.
If the domain contains at least one * or ? character then the Object Name is a pattern. These characters cannot be used in the name of an MBean, only when matching MBeans.
The domain cannot contain the colon character ( :).
```
You can view more details from [this link].(https://www.oracle.com/java/technologies/javase/management-extensions-best-practices.html#mozTocId805713)

**Solution**
I think the best way is to constraint the name of resourse.

**Comment by sczyh30** [comment]
cc @brotherlu-xcq @garroshh Any suggestions?

**Comment by garroshh** [comment]
agree with @BlueSodaWater

Generally speaking，MBean name not include (* ? = : " \n)

javax.management.ObjectName.construct at line 606
![image](https://user-images.githubusercontent.com/22784106/206104476-76e6b3d8-92a6-4773-9787-26a2b5591bc9.png)

**Comment by sczyh30** [comment]
> I think the best way is to constraint the name of resource.

This could bring incompatibility, and it should not be a constraint of Sentinel itself. Any other workaround ideas?

**Comment by LiYangSir** [comment]
Is it possible to add a layer of escaping? Trying to use the following way is working fine.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/50188356/206131198-d8e891ac-cee7-49fa-b40e-e4cb3c4a2848.png">

**Comment by LiYangSir** [comment]
If there are special characters, they can be escaped before registration by calling "ObjectName.quote()" method:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/50188356/206139410-f79602b5-a8f4-4aa4-9638-268a8faa5046.png">

**Comment by sczyh30** [comment]
> Is it possible to add a layer of escaping? Trying to use the following way is working fine. <img alt="image" width="461" src="https://user-images.githubusercontent.com/50188356/206131198-d8e891ac-cee7-49fa-b40e-e4cb3c4a2848.png">

Maybe we could just "quote" the resource name when exporting to JMX? @LiYangSir

**Comment by sczyh30** [comment]
cc @xiangtianyu @garroshh @BlueSodaWater refer https://github.com/alibaba/Sentinel/pull/2992

**Comment by wapkch** [comment]
## Issue Still Exists - Request to Reopen

Hi @sczyh30 @LiYangSir,

I've reviewed PR #2992 and found that **the issue is not completely resolved**. The problem still exists in certain scenarios.

### Root Cause Analysis

According to the [[JMX ObjectName specification](https://docs.oracle.com/javase/8/docs/api/javax/management/ObjectName.html)](https://docs.oracle.com/javase/8/docs/api/javax/management/ObjectName.html), the `ObjectName.quote()` method has limitations:

1. **`quote()` only works for the VALUE part** of key-value pairs.
2. **It does NOT work for the KEY part** or when special characters appear in certain contexts.

### The Problem with Current Fix

Looking at the current implementation in `MBeanRegistry.java`:

```java
ObjectName objectName = new ObjectName(
    domain + ":type=" + type + ",name=\"" + resourceName + "\",classification=\"" + classification + "\""
);

```

Even after applying `ObjectName.quote()` to `resourceName`, the resulting ObjectName like:
`Sentinel:type=com.example.App,name="*HelloWorld",classification="0"`

**This is still invalid** because:

* The `*` character in the name value is treated as a pattern character by JMX.
* According to ObjectName javadoc: *"If the domain contains at least one * or ? character then the Object Name is a pattern. These characters cannot be used in the name of an MBean, only when matching MBeans."*

### Evidence

From the [[ObjectName source code](https://github.com/openjdk/jdk/blob/master/src/java.management/share/classes/javax/management/ObjectName.java)](https://github.com/openjdk/jdk/blob/master/src/java.management/share/classes/javax/management/ObjectName.java) (line 555):

```java
case '*' :
case '?' :
    setDomainPattern(true);
    index++;
    break;

```

The `*` character triggers pattern mode even when quoted in certain contexts.

When using a resource name like *HelloWorld, the following exception is thrown:

```Plaintext
javax.management.MalformedObjectNameException: Invalid character '*' in key part of property
	at java.management/javax.management.ObjectName.construct(ObjectName.java:555) ~[na:na]
	at java.management/javax.management.ObjectName.<init>(ObjectName.java:1405) ~[na:na]
```
