### ISSUE TITLE
sentinel-transport-simple-http SPI throws “not a subtype” ServiceConfigurationError

### ISSUE THREAD

**Issue by CarpenterLee** [alibaba/Sentinel#300]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

When start sentinel-dashboard in IntelliJ IDEA, if we use absolute dependency of `sentinel-transport-simple-http` instead of a module dependency, a `ServiceConfigurationError` "not a subtype" will be thrown, for that the classloader of `CommandCenter` and `SimpleHttpCommandCenter` is not the same.

The exception is as flow:

![image](https://user-images.githubusercontent.com/18542108/49798074-5d6d0d00-fd7c-11e8-8ea0-130a6618e803.png)

```
java.util.ServiceConfigurationError: com.alibaba.csp.sentinel.transport.CommandCenter: Provider com.alibaba.csp.sentinel.transport.command.SimpleHttpCommandCenter not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.alibaba.csp.sentinel.transport.init.CommandCenterInitFunc.init(CommandCenterInitFunc.java:35)
	at com.alibaba.csp.sentinel.init.InitExecutor.doInit(InitExecutor.java:52)
	at com.alibaba.csp.sentinel.Env.<clinit>(Env.java:32)
	at com.alibaba.csp.sentinel.Constants.<clinit>(Constants.java:40)
	at com.alibaba.csp.sentinel.context.ContextUtil.initDefaultContext(ContextUtil.java:68)
	at com.alibaba.csp.sentinel.context.ContextUtil.<clinit>(ContextUtil.java:62)
	at com.alibaba.csp.sentinel.adapter.servlet.CommonFilter.doFilter(CommonFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

To solve this problem, we could package sentinel-dashboard as a fat jar:
```shell
mvn clean package
```
and run the jar directly.
```shell
java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080  -jar sentinel-dashboard.jar
```

### Describe what you expected to happen

The SPI implementation should be loaded correctly

### How to reproduce it (as minimally and precisely as possible)

1. replace dependency in `sentinel-dashboard.xml` from 
```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-transport-simple-http</artifactId>
    <version>${project.version}</version>
</dependency>
```
to 
```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-transport-simple-http</artifactId>
    <version>0.1.0</version>
</dependency>
```
2. run `DashboardApplication` in intelliJ IDEA

### Tell us your environment
Mac 10.12.6 
java version "11.0.1" 2018-10-16 LTS

### Anything else we need to know?
none.

**Comment by cdfive** [comment]
I tried with the reproduce steps, the same Exception was thrown.

Tried making a breakpoint in `if (!service.isAssignableFrom(c)) { `  of  `ServiceLoader` class

There are 2 ClassLoader found:
SimpleHttpCommandCenter=>sun.misc.Launcher.AppClassLoader
CommandCenter=>org.springframework.boot.devtools.restart.classloader.RestartClassLoader

Learned from springboot doc:
`By default, any open project in your IDE is loaded with the “restart” classloader, and any regular .jar file is loaded with the “base” classloader.`

see:
https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload

add META-INF/spring-devtools.properties file in resources folder,

**Comment by CarpenterLee** [comment]
Thanks for your elaborate solution @cdfive :smile:
