### ISSUE TITLE
sentinel graalvm spi 重复加载问题

### ISSUE THREAD

**Issue by ruansheng8** [alibaba/Sentinel#3012]
## Issue Description

Spring Boot使用 `sentinel-core`模块时,打包成native镜像 , spi被加载了2次

### How to reproduce it (as minimally and precisely as possible)

1. 复现demo
```java
package com.demo;

import com.alibaba.csp.sentinel.Entry;
import com.alibaba.csp.sentinel.SphU;
import com.alibaba.csp.sentinel.slots.block.BlockException;
import com.alibaba.csp.sentinel.slots.block.RuleConstant;
import com.alibaba.csp.sentinel.slots.block.flow.FlowRule;
import com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
public class NativeDemoApp {

    private static final String RES_KEY = "test";

    public static void main(String[] args) {
        SpringApplication.run(NativeDemoApp.class, args);
        init();
        System.out.println("========== 开始执行测试方法 ==========");
        for (int i = 0; i < 3; i++) {
            String result = test(i);
            System.out.println(String.format("========== 第%s次执行结果: %s ==========", i + 1, result));
        }
    }

    public static void init() {
        System.out.println("========== 开始加载sentinel规则... ==========");
        List<FlowRule> rules = new ArrayList<FlowRule>();
        FlowRule rule1 = new FlowRule();
        rule1.setResource(RES_KEY);
        // Set max qps to 20
        rule1.setCount(1);
        rule1.setGrade(RuleConstant.FLOW_GRADE_QPS);
        rule1.setLimitApp("default");
        rules.add(rule1);
        FlowRuleManager.loadRules(rules);
        System.out.println("========== sentinel规则加载完成! ==========");
    }


    public static String test(int i) {
        Entry entry = null;
        try {
            entry = SphU.entry(RES_KEY);
        } catch (BlockException ex) {
            return "BlockException...";
        } finally {
            if (entry != null) {
                entry.exit();
            }
        }
        return "调用成功!";
    }


}

```

Maven 相关配置
```xml
    <properties>
        <java.version>17</java.version>
        <sentinel.version>1.8.6</sentinel.version>
    </properties>
    <dependencies>
    
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>${sentinel.version}</version>
        </dependency>
    
    
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>
                        -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/
                    </jvmArguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

2. 执行`mvn -Pnative spring-boot:run` 来生成反射文件
3. 执行 `mvn -Pnative native:compile` 生成native镜像
4. 生成后执行对应的镜像可以看到以下错误
```java
**2023-01-03T19:11:36.354+08:00  INFO 20736 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-01-03T19:11:36.354+08:00  INFO 20736 --- [           main] com.demo.NativeDemoApp                   : Started NativeDemoApp in 0.124 seconds (process running for 0.129)
========== 开始加载sentinel规则... ==========
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: C:\Users\ruanx\logs\csp\
INFO: Sentinel log name use pid is: false
INFO: Sentinel log level is: INFO
========== sentinel规则加载完成! ==========
========== 开始执行测试方法 ==========
com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.init.InitFunc]Found repeat alias name for com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit and com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit,SPI configuration file=META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.load(SpiLoader.java:383)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadInstanceListSorted(SpiLoader.java:169)
        at com.alibaba.csp.sentinel.init.InitExecutor.doInit(InitExecutor.java:46)
        at com.alibaba.csp.sentinel.Env.<clinit>(Env.java:36)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:85)
        at com.demo.NativeDemoApp.test(NativeDemoApp.java:63)
        at com.demo.NativeDemoApp.main(NativeDemoApp.java:40)
Exception in thread "main" com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.slotchain.SlotChainBuilder]Found repeat alias name for com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder and com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder,SPI configuration file=META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.load(SpiLoader.java:383)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadFirstInstanceOrDefault(SpiLoader.java:229)
        at com.alibaba.csp.sentinel.slotchain.SlotChainProvider.newSlotChain(SlotChainProvider.java:44)
        at com.alibaba.csp.sentinel.CtSph.lookProcessChain(CtSph.java:205)
        at com.alibaba.csp.sentinel.CtSph.entryWithPriority(CtSph.java:136)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:176)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:315)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:85)
        at com.demo.NativeDemoApp.test(NativeDemoApp.java:63)
        at com.demo.NativeDemoApp.main(NativeDemoApp.java:40)**
```

预期正确的执行结果:
```
2023-01-03T19:17:15.920+08:00  INFO 21724 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-01-03T19:17:15.926+08:00  INFO 21724 --- [           main] com.demo.NativeDemoApp                   : Started NativeDemoApp in 1.057 seconds (process running for 1.52)
========== 开始加载sentinel规则... ==========
========== sentinel规则加载完成! ==========
========== 开始执行测试方法 ==========
========== 第1次执行结果: 调用成功! ==========
========== 第2次执行结果: BlockException... ==========
========== 第3次执行结果: BlockException... ==========
```
### Tell us your environment
Windows 11 , JDK17 , Spring Boot 3.0

### Anything else we need to know?

是由于`mvn -Pnative spring-boot:run` 这一步在`reflect-config.json`文件会添加以下配置
```json
// 这里省略其他相关配置
{
  "name":"com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder",
  "methods":[{"name":"<init>","parameterTypes":[] }]
}
```
从而导致SPI被加载了2次

如果省略 `mvn -Pnative spring-boot:run`  这一步(`reflect-config.json`文件中不包含上面的反射配置) , 直接执行 `mvn -Pnative native:compile` 生成native镜像 , 则程序符合预期.

目前想到的解决方案是修改`SpiLoader.java line:399 ` 的判断逻辑 , 对于重复的加载的类将错误改为警告
```java
                    if (classMap.containsKey(aliasName)) {
                        Class<? extends S> existClass = classMap.get(aliasName);
                        fail("Found repeat alias name for " + clazz.getName() + " and "
                                + existClass.getName() + ",SPI configuration file=" + fullFileName);
                    }
```

**Comment by sczyh30** [comment]
cc @cdfive @LearningGp

**Comment by drgnchan** [comment]
我重现了问题，而且发现不执行`mvn -Pnative spring-boot:run`，直接执行`mvn -Pnative native:compile`的话，会产生一样的报错。

1. 删除`/META-INF/native-image`下的文件
2. 执行`mvn -Pnative native:compile`，生成的[reflect-config.json](https://gist.github.com/drgnchan/a4e205fdbc5f0b15b55e3d4e520cd741)


3. 运行生成的image二进制文件
4. 报错：
```
...(省略)

2023-01-04T11:44:57.357+08:00  INFO 87428 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 193 ms
2023-01-04T11:44:57.513+08:00  INFO 87428 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-01-04T11:44:57.519+08:00  INFO 87428 --- [           main] c.e.s.SentinelGraalvmApplication         : Started SentinelGraalvmApplication in 0.529 seconds (process running for 0.614)
========== 开始加载sentinel规则... ==========
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: /Users/raymond/logs/csp/
INFO: Sentinel log name use pid is: false
INFO: Sentinel log level is: INFO
========== sentinel规则加载完成! ==========
========== 开始执行测试方法 ==========
com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.init.InitFunc]Found repeat alias name for com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit and com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit,SPI configuration file=META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.load(SpiLoader.java:383)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadInstanceListSorted(SpiLoader.java:169)
        at com.alibaba.csp.sentinel.init.InitExecutor.doInit(InitExecutor.java:46)
        at com.alibaba.csp.sentinel.Env.<clinit>(Env.java:36)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:85)
        at com.example.sentinelgraalvm.SentinelGraalvmApplication.test(SentinelGraalvmApplication.java:47)
        at com.example.sentinelgraalvm.SentinelGraalvmApplication.main(SentinelGraalvmApplication.java:24)
Exception in thread "main" com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.slotchain.SlotChainBuilder]Found repeat alias name for com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder and com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder,SPI configuration file=META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.load(SpiLoader.java:383)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadFirstInstanceOrDefault(SpiLoader.java:229)
        at com.alibaba.csp.sentinel.slotchain.SlotChainProvider.newSlotChain(SlotChainProvider.java:44)
        at com.alibaba.csp.sentinel.CtSph.lookProcessChain(CtSph.java:205)
        at com.alibaba.csp.sentinel.CtSph.entryWithPriority(CtSph.java:136)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:176)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:315)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:85)
        at com.example.sentinelgraalvm.SentinelGraalvmApplication.test(SentinelGraalvmApplication.java:47)
        at com.example.sentinelgraalvm.SentinelGraalvmApplication.main(SentinelGraalvmApplication.java:24)

```

**Comment by ruansheng8** [comment]
@drgnchan `reflect-config.json`  文件里面有 `DefaultSlotChainBuilder` 相关内容吗 , 如果有 , 可以尝试把`main`函数里面的`init()`以及下面的逻辑移到controller去触发 (这样SpringBoot启动的时候就不会执行init和相关限流逻辑 , 应该不会生成对应的反射配置)

**Comment by ruansheng8** [comment]
@drgnchan  从你的运行日志来看 , 似乎不是windows环境 ,  或许这跟操作系统有关 (有待确认) , 我这边在windows 11 环境下 , 不同的机器均打包了一次 , 在windows 下 直接使用`mvn -Pnative native:compile` 依然可以正常工作 . 
下面是基于windows直接运行`.exe`文件的结果
![image](https://user-images.githubusercontent.com/24709538/210483343-289c1785-23ad-4184-91a6-6229276afc26.png)

**Comment by drgnchan** [comment]
> @drgnchan 从你的运行日志来看 , 似乎不是windows环境 , 或许这跟操作系统有关 (有待确认) , 我这边在windows 11 环境下 , 不同的机器均打包了一次 , 在windows 下 直接使用`mvn -Pnative native:compile` 依然可以正常工作 (只当 reflect-config.json 文件存在对应的反射配置时 , 才会报错). 下面是基于windows直接运行`.exe`文件的结果 ![image](https://user-images.githubusercontent.com/24709538/210483343-289c1785-23ad-4184-91a6-6229276afc26.png)

我的环境是macOS Ventura 13.1。

**Comment by Deathef** [comment]
我在Linux上试了，不管是否执行`mvn -Pnative spring-boot:run`都会这个错误。

```
.....省略

2023-01-04T17:48:29.883+08:00  INFO 2596766 --- [           main] com.demo.NativeDemoApp                   : Started NativeDemoApp in 0.049 seconds (process running for 0.053)
========== 开始加载sentinel规则... ==========
INFO: Sentinel log output type is: file
INFO: Sentinel log charset is: utf-8
INFO: Sentinel log base directory is: /home/Death/logs/csp/
INFO: Sentinel log name use pid is: false
INFO: Sentinel log level is: INFO
========== sentinel规则加载完成! ==========
========== 开始执行测试方法 ==========
com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.init.InitFunc]Found repeat alias name for com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit and com.alibaba.csp.sentinel.metric.extension.MetricCallbackInit,SPI configuration file=META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.load(SpiLoader.java:383)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadInstanceListSorted(SpiLoader.java:169)
        at com.alibaba.csp.sentinel.init.InitExecutor.doInit(InitExecutor.java:46)
        at com.alibaba.csp.sentinel.Env.<clinit>(Env.java:36)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:85)
        at com.demo.NativeDemoApp.test(NativeDemoApp.java:47)
        at com.demo.NativeDemoApp.main(NativeDemoApp.java:24)
Exception in thread "main" com.alibaba.csp.sentinel.spi.SpiLoaderException: [com.alibaba.csp.sentinel.slotchain.SlotChainBuilder]Found repeat alias name for com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder and com.alibaba.csp.sentinel.slots.DefaultSlotChainBuilder,SPI configuration file=META-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder
        at com.alibaba.csp.sentinel.spi.SpiLoader.fail(SpiLoader.java:525)
        at com.alibaba.csp.sentinel.spi.SpiLoader.load(SpiLoader.java:383)
        at com.alibaba.csp.sentinel.spi.SpiLoader.loadFirstInstanceOrDefault(SpiLoader.java:229)
        at com.alibaba.csp.sentinel.slotchain.SlotChainProvider.newSlotChain(SlotChainProvider.java:44)
        at com.alibaba.csp.sentinel.CtSph.lookProcessChain(CtSph.java:205)
        at com.alibaba.csp.sentinel.CtSph.entryWithPriority(CtSph.java:136)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:176)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:315)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:85)
        at com.demo.NativeDemoApp.test(NativeDemoApp.java:47)
        at com.demo.NativeDemoApp.main(NativeDemoApp.java:24)
2023-01-04T17:48:33.622+08:00  INFO 2596766 --- [ionShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2023-01-04T17:48:33.622+08:00  INFO 2596766 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
```

Linux (Kernel 5.15.77-amd64-desktop)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode, sharing)
Spring Boot 3.0.1

**Comment by ralf0131** [comment]
I can reproduce the issue with the given demo. The issue can also be eliminated by removing the following lines in `resource-config.json` generated by `mvn -Pnative spring-boot:run`

```
    {
      "pattern":"\\QMETA-INF/services/com.alibaba.csp.sentinel.init.InitFunc\\E"
    }, 
    {
      "pattern":"\\QMETA-INF/services/com.alibaba.csp.sentinel.slotchain.ProcessorSlot\\E"
    }, 
    {
      "pattern":"\\QMETA-INF/services/com.alibaba.csp.sentinel.slotchain.SlotChainBuilder\\E"
    }, 
```

The root cause of this issue is that the above resources has already been added automatically by Spring-boot (my guess),  by adding these lines the resource will be added twice so that `Classloader.getResource` would load twice of a specific url. 

To verify my guess, I have even simplified the code to the following demo:

```java
public static void main(String[] args) throws Exception {
        SpringApplication.run(DemoApplication.class, args);

        Enumeration<URL> urls = InitFunc.class.getClassLoader().
                getResources("META-INF/services/com.alibaba.csp.sentinel.init.InitFunc");
        while (urls.hasMoreElements()) {
            URL url = urls.nextElement();
            System.out.println(url);
        }
    }
```

If we run `mvn -Pnative native:compile` without `mvn -Pnative spring-boot:run`, the output will be:

```
resource:/META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
```

However, if we add the following lines to `resource-config.json`

```
    {
      "pattern":"\\QMETA-INF/services/com.alibaba.csp.sentinel.init.InitFunc\\E"
    }, 
```

and run `mvn -Pnative native:compile`  again, the ouput will be 

```
resource:/META-INF/services/com.alibaba.csp.sentinel.init.InitFunc
resource:/META-INF/services/com.alibaba.csp.sentinel.init.InitFunc#1
```

This shows putting a line to `resource-config.json` will add an extra entry URL for `ClassLoader.getResources`.
So I think this is not an issue on the sentinel side, and what `mvn -Pnative spring-boot:run` gives to us is not 100% accurate. Removing such lines in `resource-config.json` should solve the issue.
