### ISSUE TITLE
第一次执行com.alibaba.csp.sentinel.SphU#entry(java.lang.String)会觉得很慢

### ISSUE THREAD

**Issue by junplus** [alibaba/Sentinel#311]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
第一次执行com.alibaba.csp.sentinel.SphU#entry(java.lang.String)会觉得很慢

### Anything else we need to know?
MetricTimerListener在初始化的过程中会创建一个MetricWriter对象，该类的对象里面会调用getPid()并且最终调用InetAddress.getLocalHost()，目前我这边通过调用com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager#getRules()来预先初始化MetricTimerListener，有没有更好的办法？

下面是调用栈：
"main" #1 prio=5 os_prio=31 tid=0x00007fe10080b000 nid=0x2803 runnable [0x0000700007965000]
   java.lang.Thread.State: RUNNABLE
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        - locked <0x000000076ba7bea0> (a java.lang.Object)
        at sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:140)
        at sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
        at com.alibaba.csp.sentinel.util.PidUtil.getPid(PidUtil.java:26)
        at com.alibaba.csp.sentinel.node.metric.MetricWriter.<init>(MetricWriter.java:80)
        at com.alibaba.csp.sentinel.node.metric.MetricTimerListener.<clinit>(MetricTimerListener.java:33)
        at com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager.<clinit>(FlowRuleManager.java:64)
        at com.alibaba.csp.sentinel.slots.block.flow.FlowSlot.entry(FlowSlot.java:117)
        at com.alibaba.csp.sentinel.slots.block.flow.FlowSlot.entry(FlowSlot.java:111)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slots.block.authority.AuthoritySlot.entry(AuthoritySlot.java:39)
        at com.alibaba.csp.sentinel.slots.block.authority.AuthoritySlot.entry(AuthoritySlot.java:33)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slots.system.SystemSlot.entry(SystemSlot.java:36)
        at com.alibaba.csp.sentinel.slots.system.SystemSlot.entry(SystemSlot.java:30)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slots.statistic.StatisticSlot.entry(StatisticSlot.java:54)
        at com.alibaba.csp.sentinel.slots.statistic.StatisticSlot.entry(StatisticSlot.java:48)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slots.logger.LogSlot.entry(LogSlot.java:35)
        at com.alibaba.csp.sentinel.slots.logger.LogSlot.entry(LogSlot.java:29)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterBuilderSlot.entry(ClusterBuilderSlot.java:103)
        at com.alibaba.csp.sentinel.slots.clusterbuilder.ClusterBuilderSlot.entry(ClusterBuilderSlot.java:48)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slots.nodeselector.NodeSelectorSlot.entry(NodeSelectorSlot.java:171)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.fireEntry(AbstractLinkedProcessorSlot.java:32)
        at com.alibaba.csp.sentinel.slotchain.DefaultProcessorSlotChain$1.entry(DefaultProcessorSlotChain.java:31)
        at com.alibaba.csp.sentinel.slotchain.AbstractLinkedProcessorSlot.transformEntry(AbstractLinkedProcessorSlot.java:40)
        at com.alibaba.csp.sentinel.slotchain.DefaultProcessorSlotChain.entry(DefaultProcessorSlotChain.java:75)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:157)
        at com.alibaba.csp.sentinel.CtSph.entry(CtSph.java:300)
        at com.alibaba.csp.sentinel.SphU.entry(SphU.java:86)
        at retry.RetryDemo.testSphU(RetryDemo.java:71)
        at retry.RetryDemo.main(RetryDemo.java:53)

**Comment by CarpenterLee** [comment]
The first   `com.alibaba.csp.sentinel.SphU#entry()` invocation will trigger Sentinel's initialization, which will cost a period of time. The real initialization is done in `com.alibaba.csp.sentinel.Env`'s static code block, so you could explicitly trigger the initialization at your app's beginning. Just call `System.out.println(Env.class)` or something like this.
