### ISSUE TITLE
sentinel-demo-nacos-datasource  ClassNotFoundException: Logger

### ISSUE THREAD

**Issue by pig4cloud** [alibaba/Sentinel#437]
### Describe what happened (or what feature you want)
When I used  sentinel-demo-nacos-datasource  NacosConfigSender.main
`
Mon Jan 21 15:50:44 CST 2019 sun.misc.Launcher$AppClassLoader@135fbaa4 JM.Log:WARN Init JM logger with NopLoggerFactory, pay attention. sun.misc.Launcher$AppClassLoader@135fbaa4
java.lang.ClassNotFoundException: org.apache.logging.log4j.core.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.nacos.client.logger.log4j2.Log4j2LoggerFactory.<init>(Log4j2LoggerFactory.java:33)
`

### Describe what you expected to happen
true/fasle push
### How to reproduce it (as minimally and precisely as possible)

Just do it

### Tell us your environment
java version "1.8.0_171"
macos 10.13.2
sentinel 1.4.2-SNAPSHOT

**Comment by pig4cloud** [comment]
need add log dependency ，logback or other

**Comment by pig4cloud** [comment]
I already pull request，But I don't confirm if other example projects have this problem.
