### ISSUE TITLE
Run dubbo demo FooProviderBootstrap fail

### ISSUE THREAD

**Issue by qq925716471** [alibaba/Sentinel#530]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
run FooProviderBootstrap.main() fail

Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/spring/beans/factory/annotation/AnnotationInjectedBeanPostProcessor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.dubbo.config.spring.context.annotation.DubboComponentScanRegistrar.registerReferenceAnnotationBeanPostProcessor(DubboComponentScanRegistrar.java:90)
	at com.alibaba.dubbo.config.spring.context.annotation.DubboComponentScanRegistrar.registerBeanDefinitions(DubboComponentScanRegistrar.java:61)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:358)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:357)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:328)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at com.alibaba.csp.sentinel.demo.dubbo.demo1.FooProviderBootstrap.main(FooProviderBootstrap.java:50)
Caused by: java.lang.ClassNotFoundException: com.alibaba.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
### How to reproduce it (as minimally and precisely as possible)
1. check out master
2. run com.alibaba.csp.sentinel.demo.dubbo.demo1.FooProviderBootstrap.main()

### Tell us your environment
branch: master

sentinel-demo-dubbo dubbo version is 2.6.5  class ReferenceAnnotationBeanPostProcessor extends AnnotationInjectedBeanPostProcessor.
When I change dubbo version to 2.5.8 it is ok .
class ReferenceAnnotationBeanPostProcessor extends InstantiationAwareBeanPostProcessorAdapter

**Comment by sczyh30** [comment]
Fixed in #534.
