### ISSUE TITLE
Sentilel-dashboard failed to add FlowRuleNacosProvider to compile

### ISSUE THREAD

**Issue by ShZhengqin** [alibaba/Sentinel#600]
## Issue Description

Type: *bug report*
下载了sentinel最新源码，在sentinel-dashboard中将 src/test/java中的4个类：
FlowRuleNacosProvider.java
FlowRuleNacosPublisher.java
NacosConfig.java
NacosConfigUtil.java
提取出来放在了src/main/java的包： com.alibaba.csp.sentinel.dashboard.rule.nacos下，如图
![图片](https://user-images.githubusercontent.com/28048110/54744135-1c995580-4c01-11e9-9a9e-7b6bfe537467.png)

编译 maven clean package  报错：
![图片](https://user-images.githubusercontent.com/28048110/54744202-43578c00-4c01-11e9-89de-66aa0ce80da0.png)

望解答，谢谢

**Comment by sczyh30** [comment]
Hi, you need to add Nacos client dependency (`nacos-client`) when you're using the Nacos publisher demo.

**Comment by ShZhengqin** [comment]
@sczyh30 谢谢， 已经可以编译通过，现在有个疑问请教：
我在nacos上添加了一个 service-demo-flow-rules 如图
![图片](https://user-images.githubusercontent.com/28048110/54804847-f41c6480-4caf-11e9-9bff-aa1abb2c447b.png)
在 sentinel-dashboard上可以看到已获取到这个数据，如图
![图片](https://user-images.githubusercontent.com/28048110/54804879-131af680-4cb0-11e9-92ef-362aded0c083.png)
![图片](https://user-images.githubusercontent.com/28048110/54804891-1dd58b80-4cb0-11e9-848c-93ddcd1f636b.png)

我测试下来，发现，在nacos上修改某个属性，如【count】的值，/v2/flow/rules可以正确获取， sentinel-dashboard上也可以正确显示，规则也生效了。但反过来，我在sentinel-dashboard上修改此属性值=2时，如图
![图片](https://user-images.githubusercontent.com/28048110/54804978-6e4ce900-4cb0-11e9-9fcd-3d7938b417a9.png)
Nacos上不能正常显示，依然还是【count: 6.0】, /v2/flow/rules接口也依然没有变,count也是=6，但sentinel的规则生效了，是按着【count: 2.0】的限流规则来执行的，如图
![图片](https://user-images.githubusercontent.com/28048110/54805116-df8c9c00-4cb0-11e9-8368-557fbc1de6ff.png)

请问这是为什么？
我希望sentinel-dashboard上修改属性值的时候，nacos对应的属性也能更改，改如何处理？
thanks

**Comment by sczyh30** [comment]
如果已经接入了配置源，需要在应用维度规则管理页面进行推送（`/v2/flow`），请手动切换 URL 至 v2 URL (`/flow/xxx` -> `/v2/flow/xxx`)，或者直接修改前端路由。

**Comment by ShZhengqin** [comment]
@sczyh30 ,thanks so much

**Comment by ShZhengqin** [comment]
@sczyh30 , 我仿照FlowControllerV2写了一个 ParamFlowRuleControllerV2， 请看 https://github.com/ShZhengqin/sentinel-dashboard， 相关的v2的js文件都已经仿照flow改造完成，现在遇到的问题是，页面上新增ParamFlow没有问题，但获取数据后页面展示时报错，报错内容如下：
     
      `2019-03-26 14:40:21 [http-nio-8080-exec-6] INFO  c.a.c.s.d.r.n.ParamFlowRuleNacosProvider - ParamFlowRule rules:[{"app":"service-demo","clusterConfig":{"fallbackToLocalWhenFail":false,"sampleCount":10,"thresholdType":0,"windowIntervalMs":1000},"clusterMode":false,"count":1.0,"gmtCreate":1553582394195,"gmtModified":1553582394195,"grade":1,"id":2,"ip":"192.168.105.121","limitApp":"default","paramFlowItemList":[],"paramIdx":1,"port":8720,"resource":"/test","rule":{"clusterConfig":{"$ref":"$[0].clusterConfig"},"clusterMode":false,"count":1.0,"grade":1,"limitApp":"default","paramFlowItemList":[],"paramIdx":1,"resource":"/test"}}]
2019-03-26 14:40:21 [http-nio-8080-exec-6] ERROR c.a.c.s.d.c.v.ParamFlowRuleControllerV2 - Error when querying paramFlow rules
com.alibaba.fastjson.JSONException: set property error, com.alibaba.csp.sentinel.dashboard.datasource.entity.rule.ParamFlowRuleEntity#paramFlowItemList
	at com.alibaba.fastjson.parser.deserializer.FieldDeserializer.setValue(FieldDeserializer.java:162)
	at com.alibaba.fastjson.parser.deserializer.ArrayListTypeFieldDeserializer.parseField(ArrayListTypeFieldDeserializer.java:71)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1183)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:822)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:273)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:269)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:762)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:696)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:691)
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:593)
	at com.alibaba.csp.sentinel.dashboard.rule.nacos.NacosConfig.lambda$paramFlowRuleEntityDecoder$3(NacosConfig.java:101)
	at com.alibaba.csp.sentinel.dashboard.rule.nacos.ParamFlowRuleNacosProvider.getRules(ParamFlowRuleNacosProvider.java:57)
	at com.alibaba.csp.sentinel.dashboard.rule.nacos.ParamFlowRuleNacosProvider.getRules(ParamFlowRuleNacosProvider.java:39)
	at com.alibaba.csp.sentinel.dashboard.controller.v2.ParamFlowRuleControllerV2.apiQueryMachineRules(ParamFlowRuleControllerV2.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.csp.sentinel.adapter.servlet.CommonFilter.doFilter(CommonFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.csp.sentinel.dashboard.config.WebConfig$1.doFilter(WebConfig.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.fastjson.parser.deserializer.FieldDeserializer.setValue(FieldDeserializer.java:96)
	... 73 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.csp.sentinel.dashboard.datasource.entity.rule.ParamFlowRuleEntity.getParamFlowItemList(ParamFlowRuleEntity.java:75)
	... 78 common frames omitted
`

其他规则，如SystemRule, AuthorityRule我也写了，新删改都没有问题， 只有ParamFlow这个有问题，dashboard页面如下
![图片](https://user-images.githubusercontent.com/28048110/54977332-ecbec900-4fd7-11e9-9e8d-d387909a276c.png)

**Comment by ShZhengqin** [comment]
Hi, @sczyh30 , 我改了下代码，bug消除了， https://github.com/ShZhengqin/sentinel-dashboard/edit/master/NacosConfig.java 的101行，和 https://github.com/ShZhengqin/sentinel-dashboard/blob/master/ParamFlowRuleEntity.java 的48行
