### ISSUE TITLE
FileWritableDataSource :file:/xx/xx.jar!/BOOT-INF/classes!/FlowRule.json (no such file or directory)

### ISSUE THREAD

**Issue by dqing0** [alibaba/Sentinel#634]
## Issue Description

FileWritableDataSource ：file:/xx/xx.jar!/BOOT-INF/classes!/FlowRule.json (没有那个文件或目录)
at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.alibaba.csp.sentinel.datasource.FileWritableDataSource.write(FileWritableDataSource.java:73)
	at com.alibaba.csp.sentinel.command.handler.ModifyRulesCommandHandler.writeToDataSource(ModifyRulesCommandHandler.java:108)
	at com.alibaba.csp.sentinel.command.handler.ModifyRulesCommandHandler.handle(ModifyRulesCommandHandler.java:68)
	at com.alibaba.csp.sentinel.transport.command.http.HttpEventTask.run(HttpEventTask.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

### Describe what happened (or what feature you want)
i wanted to load local FlowRule.json,when i run application with jar,i found the error.
i think the **new File(filepath)** method  dont work,when the file in jar

**Comment by sczyh30** [comment]
Hi, please check whether your file path is correct.

**Comment by dqing0** [comment]
file path is correct, when i use intellij ,it work.But ,when i package, use 'java -jar xx.jar',it faild.  i think the reason is that  the method **new File(path) ** cannot read the file in jar

**Comment by sczyh30** [comment]
Maybe you can try this: https://stackoverflow.com/questions/20389255/reading-a-resource-file-from-within-jar

**Comment by fangjian0423** [comment]
@sczyh30 

`FileRefreshableDataSource` needs `java.io.File` as constructor parameter and we couldn't get file in jar.

Maybe we need `java.io.InputStream` as the constructor parameter of `FileRefreshableDataSource`.

Then we could write a overload constructor method to accept `java.io.InputStream`.

**Comment by dqing0** [comment]
i know the way,but the load file  in your sentinel-datasource-extension.jar,i cant rewrite

**Comment by dqing0** [comment]
> @sczyh30
> 
> `FileRefreshableDataSource` needs `java.io.File` as constructor parameter and we couldn't get file in jar.
> 
> Maybe we need `java.io.InputStream` as the constructor parameter of `FileRefreshableDataSource`.
> 
> Then we could write a overload constructor method to accept `java.io.InputStream`.

you are right

**Comment by fangjian0423** [comment]
@dqing0 

welcome to contribute. You could create pull request to enhance it.

**Comment by dqing0** [comment]
> @dqing0
> 
> welcome to contribute. You could create pull request to enhance it.

fine,i will do that,thanks @fangjian0423 @sczyh30

**Comment by sczyh30** [comment]
Contributions are welcomed :)
