### ISSUE TITLE
ErrCode:-400,ErrMsg:null & Nacos config service has not been initialized or error occurred

### ISSUE THREAD

**Issue by rexlin600** [alibaba/Sentinel#712]
when i use nacos 1.0.0 and sentinel 1.6.0，there has a mistake

```log
INFO: log base dir is: C:\Users\Less\logs\csp\
INFO: log name use pid is: false
ErrCode:-400,ErrMsg:null
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45)
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:41)
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.initNacosListener(NacosDataSource.java:127)
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.<init>(NacosDataSource.java:109)
	at org.springframework.cloud.alibaba.sentinel.datasource.factorybean.NacosDataSourceFactoryBean.getObject(NacosDataSourceFactoryBean.java:43)
	at org.springframework.cloud.alibaba.sentinel.datasource.factorybean.NacosDataSourceFactoryBean.getObject(NacosDataSourceFactoryBean.java:17)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:327)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.registerBean(SentinelDataSourceHandler.java:182)
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.lambda$afterSingletonsInstantiated$0(SentinelDataSourceHandler.java:72)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.afterSingletonsInstantiated(SentinelDataSourceHandler.java:60)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
	at com.jiuhua.spectrum.example.SpectrumExampleApplication.main(SpectrumExampleApplication.java:25)
2019-04-27 12:47:21.363 ERROR 11332 --- [           main] o.s.c.a.s.c.SentinelDataSourceHandler    : [Sentinel Starter] DataSource ds-sentinel-nacos-datasource loadConfig error: Nacos config service has not been initialized or error occurred

java.lang.IllegalStateException: Nacos config service has not been initialized or error occurred
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.readSource(NacosDataSource.java:139) ~[sentinel-datasource-nacos-1.6.0.jar:na]
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.readSource(NacosDataSource.java:42) ~[sentinel-datasource-nacos-1.6.0.jar:na]
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:44) ~[sentinel-datasource-extension-1.5.2.jar:na]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.logAndCheckRuleType(SentinelDataSourceHandler.java:195) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.registerBean(SentinelDataSourceHandler.java:184) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.lambda$afterSingletonsInstantiated$0(SentinelDataSourceHandler.java:72) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at java.util.TreeMap.forEach(TreeMap.java:1005) ~[na:1.8.0_171]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.afterSingletonsInstantiated(SentinelDataSourceHandler.java:60) [spring-cloud-alibaba-sentinel-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at com.jiuhua.spectrum.example.SpectrumExampleApplication.main(SpectrumExampleApplication.java:25) ~[classes/:na]
```

But basically the same configuration is fine in the following version：

nacos 0.8.0
sentinel 1.4.0

**Comment by sczyh30** [comment]
Seems that there were some errors during initialization of Nacos client. Which version of Spring Cloud Alibaba are you using?

**Comment by rexlin600** [comment]
i had changed my nacos version to 0.8.0 & my sentinel version is 1.4.0


besides that,u need be careful your dependency



rexlin600

------------------ Original ------------------

**Comment by kathetina** [comment]
Still, there is a problem.
my  version are nacos-1.0.0 & sentinel-1.6.0 & dubbo 2.7.2

**Comment by sczyh30** [comment]
> Still, there is a problem.
> my version are nacos-1.0.0 & sentinel-1.6.0 & dubbo 2.7.2

Could you please provide your configuration and error message?

cc @fangjian0423

**Comment by kathetina** [comment]
> Could you please provide your configuration and error message?

1、error message in my project :
INFO: log base dir is: /bomc/toptea/logs/csp/
INFO: log name use pid is: false
ErrCode:-400,ErrMsg:null
        at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45)
        at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:41)
        at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.initNacosListener(NacosDataSource.java:127)
        at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.<init>(NacosDataSource.java:109)
        at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.<init>(NacosDataSource.java:73)
        at com.ai.toptea.basic.util.NacosDataSourceUtil.init(NacosDataSourceUtil.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1759)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1696)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.apache.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
        at org.apache.dubbo.container.Main.main(Main.java:90)

2、configuration code
import com.alibaba.csp.sentinel.datasource.ReadableDataSource;
import com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource;
import com.alibaba.csp.sentinel.slots.block.flow.FlowRule;
import com.alibaba.csp.sentinel.slots.block.flow.FlowRuleManager;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.TypeReference;

public class NacosDataSourceUtil {

    public static void main(String[] args) throws Exception {
		 ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new NacosDataSource<>("10.1.130.105:8848", "sentinel-nacos", "toptea-test-flow-rules",
                source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
                }));
        FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
	}
 }
You can replace parameters and run this main function ,and then ,you can get this  error message ,like this :

ErrCode:-400,ErrMsg:null
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45)
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:41)
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.initNacosListener(NacosDataSource.java:127)
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.<init>(NacosDataSource.java:109)
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.<init>(NacosDataSource.java:73)
	at com.ai.toptea.basic.util.NacosDataSourceUtil.main(NacosDataSourceUtil.java:26)

**Comment by kathetina** [comment]
> > Still, there is a problem.
> > my version are nacos-1.0.0 & sentinel-1.6.0 & dubbo 2.7.2
> 
> Could you please provide your configuration and error message?
> 
> cc @fangjian0423

应该是nacos的问题，我试了下0.9的nacos，都没问题

**Comment by rexlin600** [comment]
nacos 0.8 is okay


发自我的iPhone

------------------ Original ------------------

**Comment by sczyh30** [comment]
The Nacos client used in 1.6.x is `1.0.0`, which should be compatible with Nacos 1.0. I've tested the Nacos datasource demo of 1.6.1 and it works.
