### ISSUE TITLE
The new degrade rule for sentinel-dashboard will fail

### ISSUE THREAD

**Issue by zhangguorong1989** [alibaba/Sentinel#78]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Adding a new degrade  rule without persistence will cause the monitor to fail

### How to reproduce it (as minimally and precisely as possible)

1. 
2018-08-22 09:48:43 receive rule change:degrade
2018-08-22 09:48:43 [{"count":1.0,"cut":false,"grade":0,"limitApp":"default","passCount":0,"resource":"pact","timeWindow":2}]
2018-08-22 09:48:43 SentinelProperty, config is real updated to: [DegradeRule{resource=null, grade=0, count=1.0, limitApp=null, timeWindow=2}]
2018-08-22 09:48:43 null
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager$RulePropertyListener.loadDegradeConf(DegradeRuleManager.java:150)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager$RulePropertyListener.configUpdate(DegradeRuleManager.java:120)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager$RulePropertyListener.configUpdate(DegradeRuleManager.java:116)
	at com.alibaba.csp.sentinel.property.DynamicSentinelProperty.updateValue(DynamicSentinelProperty.java:57)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager.loadRules(DegradeRuleManager.java:110)
	at com.alibaba.csp.sentinel.command.handler.ModifyRulesCommandHandler.handle(ModifyRulesCommandHandler.java:110)
	at com.alibaba.csp.sentinel.transport.command.http.HttpEventTask.run(HttpEventTask.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2. 
3.

**Comment by sczyh30** [comment]
Hi, please check whether your project uses **fastjson**. If so, please make sure that your fastjson version matches the fastjson version in Sentinel dependency.

**Comment by kimmking** [comment]
Check rule.getResource() is null?
Plz ensure resource is not null.

**Comment by kimmking** [comment]
@sczyh30 I think we should validate resource to avoid NPE

**Comment by sczyh30** [comment]
Yes here we should avoid NPE here. I'll fix that.
Regarding this issue, the cause might be fastjson version mismatch (causing parent fields in `AbstractRule` disappear when decoding). In dashboard we've already validated the resource name.
