### ISSUE TITLE
LogFile creation failed directly DegradeRuleManager initialization failed

### ISSUE THREAD

**Issue by winterRel** [alibaba/Sentinel#933]
某些环境没有写权限，日志文件创建失败直接导致DegradeRuleManager初始化失败，是不是可以WARN一下，日志不是强制的
Caused by: java.lang.NullPointerException
	at com.alibaba.csp.sentinel.log.DateFileLogHandler.publish(DateFileLogHandler.java:83)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at com.alibaba.csp.sentinel.log.LogBase.log(LogBase.java:99)
	at com.alibaba.csp.sentinel.log.RecordLog.info(RecordLog.java:37)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager$RulePropertyListener.configLoad(DegradeRuleManager.java:174)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager$RulePropertyListener.configLoad(DegradeRuleManager.java:155)
	at com.alibaba.csp.sentinel.property.DynamicSentinelProperty.addListener(DynamicSentinelProperty.java:40)
	at com.alibaba.csp.sentinel.slots.block.degrade.DegradeRuleManager.<clinit>(DegradeRuleManager.java:53)

**Comment by cdfive** [comment]
We can output the biz log to console by adding JVM argument `-Dcsp.sentinel.log.output.type=console` , and default is `file`.

**Comment by sczyh30** [comment]
You can also provide the log directory via `-Dcsp.sentinel.log.dir` property. It's not recommended to disable the log.
